### ISSUE TITLE
Failed to import extension

### ISSUE THREAD

**Issue by gngijben** [stefanwalther/sense-navigation#105]
### Description

Getting an error when trying to import the extension: "Failed to import extension. Please check the log file"

### Steps to Reproduce

Download ZIP from Clone/Download button. Tried with master and 1.0

##### Expected behavior

Succesvol import

##### Actual behavior

Getting error:  "Failed to import extension. Please check the log file"

##### Operating system

```
[x ] Windows
[ ] OSX
[ ] Linux
```
##### Qlik Sense

```
[ ] Desktop
[x ] Enterprise
```

##### Browser

```
[ ] Chrome
[ ] Firefox
[ ] Internet Explorer
[ ] Edge
[ ] Others: XXX
```

### Versions

* Extension version: Master / 1.0
* Browser:  Chrome
* Qlik Sense: Septemper 2017 patch 1 (qliksenseserver 11.14.4)
* Operating system: Windows server 2012 r2

Log file message:
`29	16.5.6.0	20171114T151417.984+0100	ERROR	VREDDD-QLS01	391e663e-da35-4d1e-aad1-35e94f6e58da	Command=Add extension;Result=400;ResultText=Error: PersistenceFailed	3abe45ea-aaac-4986-a666-614a7ec2eb46	de1b89cc-bbb7-4a7e-b695-5e963639cb00	0	[Account]	0	Not available	Repository	ManagementAccess	/qrs/extension/upload	Add extension	400	 ZIP file error (HTTP code: 400)	391e663e-da35-4d1e-aad1-35e94f6e58da`

**Comment by stefanwalther** [comment]
Please do not clone the entire git repo, but go to the `./build` folder where you find the different versions of the extension: https://github.com/stefanwalther/sense-navigation/tree/master/build

**Comment by stefanwalther** [comment]
@gngijben Any results? Can I close this issue?

**Comment by gngijben** [comment]
Although I still get the error occasionally, I can use the extension in my Sense apps. 
So the error message pops up but at the same time it's imported successfully because i can use it.

**Comment by stefanwalther** [comment]
OK, thx, then I am closing this issue.
