### ISSUE TITLE
The "Set Variable Value" function doesn't seem to work

### ISSUE THREAD

**Issue by rjriel** [stefanwalther/sense-navigation#107]
### Description

I created a button that has an action "Set Variable Value", however when I click the button it doesn't seem to actually set the value

### Steps to Reproduce

1. In a Sense app create a variable `vVariable` with a Definition of `1`
2. On a sheet create a KPI with a measure that has an expression `=$(vVariable)`
3. Add the sense-navigation extension to the sheet.
4. In the properties panel under `Actions` choose `Add Item`
5. In the drop down select `Set Variable Value`
6. Under `Value` put `2`. Under `Variable Name` put `vVariable`
7. Get out of Edit mode and click the newly created button

##### Expected behavior

The value of the `vVariable` variable changes to 2 and the KPI is updated

##### Actual behavior

No update actually occurs

##### Operating system

```
[ ] Windows
[x] OSX
[ ] Linux
```
##### Qlik Sense

```
[ ] Desktop
[x] Enterprise
```

##### Browser

```
[x] Chrome
[ ] Firefox
[ ] Internet Explorer
[ ] Edge
[ ] Others: XXX
```

### Versions

* Extension version: v1 Branch
* Browser: 62
* Qlik Sense: November 2017
* Operating system: High Sierra
* [Other relevant versions]

**Comment by rjriel** [comment]
In testing, it seems like line [168](https://github.com/stefanwalther/sense-navigation/blob/360edd38010599f3b24819e6d4ab05c98a4290a4/src/swr-sense-navigation.js#L168) is looking for a `variable<id>` key in `$scope.layout.props` that doesn't exist

**Comment by stefanwalther** [comment]
Closing as fixed now.
