### ISSUE TITLE
Unpublished vs Published App Functionality

### ISSUE THREAD

**Issue by michaeldburt** [stefanwalther/sense-navigation#109]
I have been using this extension to create a button that allows a user to click once, and the button selects a single value in two separate fields.  In my unpublished version of the app, this is exactly what happens.  In the published version of the application, on both the test and production servers, the button requires two clicks to select both values.

### Steps to Reproduce

1. Create button
2. Navigation Action set to None
3. Actions before Navigating enabled
4. first action, select value in field
5. second action, select value in field
6. click button, and selects multiple fields
7. publish app, try to click, and selects one field

##### Expected behavior

Would expect it to act the same in unpublished, as published

##### Actual behavior

When unpublished, the extension selects both fields with one click, as expected.

When published, the extension selects one field, and a second click selects the other field.

### Environment

Qlik Sense both Test and Production

##### Operating system

Windows Server 2012 R2

##### Qlik Sense

Qlik Sense Sept 2017
```
 Enterprise
```

##### Browser

```
[X] Chrome
[ ] Firefox
[X] Internet Explorer
[ ] Edge
[ ] Others: XXX
```

### Versions

* Extension version:  Using the latest version, found under the latest version link

**Comment by michaeldburt** [comment]
Updating this with further testing.  If i publish my app, which the button works with, the Published app will work, until the next data refresh from a reloaded QMC task.  So, it appears that the QMC Task Reload is breaking the extension.

**Comment by stefanwalther** [comment]
I am closing this because:

- This cannot be related to the extension; IMHO that must be a bug in Qlik Respository Service / QMC, so please file a bug with Qlik's support
- Another assumption could be (in case you have just uploaded the new extension), that you get an old/cached version of the extension, in that case that might have been resolved in the meanwhile?

Regards
Stefan
