### ISSUE TITLE
"Open a website / eMail" has issues in cloud

### ISSUE THREAD

**Issue by rjriel** [stefanwalther/sense-navigation#115]
### Description

When attempting to use the "Open a website / eMail" navigation behaviour, if the "open in same window" option is enabled it will be the iframe in cloud that is attempted to navigate, not the parent.

### Steps to Reproduce

1. Add Extension to an app
2. Use the "Open a website / eMail" behaviour with "Open in same window" enabled
3. View the app through an iframe and click the button.

##### Expected behavior

The browser is navigated to the expected page.

##### Actual behavior

The iframe is navigated to the expected page.

##### Operating system

```
[ ] Windows
[X] OSX
[ ] Linux
```
##### Qlik Sense

```
[ ] Desktop
[ ] Enterprise
[X] Cloud
```

##### Browser

```
[X] Chrome
[ ] Firefox
[ ] Internet Explorer
[ ] Edge
[ ] Others: XXX
```

### Versions

* Extension version: 1.0.0-rc-06
* Browser: 63.0.3239.132
* Qlik Sense: Qlik Sense Cloud - Develop environment
* Operating system: 10.13.2
* [Other relevant versions]

**Comment by rjriel** [comment]
The issue for this most likely stems from the fact that Qlik Cloud opens the app in an iframe. This is tough when trying to think about the extension in a broader sense because I can see the argument as to why a developer would only want the iframe navigated and not the parent, but in instances like Qlik Cloud you wouldn't want the user having the option to navigate just the iframe.

**Comment by stefanwalther** [comment]
Let me think about it, might be that I also just disable the feature in the cloud; I was already thinking in general of adding feature flags or somthing like that.

**Comment by stefanwalther** [comment]
yep, again thinking of it ...

In general, if I change the implementation from `window.open` to normal link, then probably the iframe issue in the cloud would not hit us. I will experiment.

**Comment by rjriel** [comment]
My suggestion was going to be checking for `window.parent` to be a value, but I haven't tested that at all

**Comment by stefanwalther** [comment]
@rjriel: I think I have a solution (working locally). Please send me instructions on slack how I can test in Qlik Cloud, thx.

**Comment by stefanwalther** [comment]
@rjriel Solved in the latest release (beta-02).
