### ISSUE TITLE
Button display with Sense Focus theme applied

### ISSUE THREAD

**Issue by jb921** [stefanwalther/sense-navigation#130]
### Description

When using the extension with the Sense Focus theme applied, the button only takes up half of the allocated space (when it's occupying a single line in the Sense designer.

### Steps to Reproduce

1. Open model with extension object
2. Click the app options (cog on the right side of the model information
3. Select "Sense Focus" theme

##### Expected behavior

Button should remain the same size as when "Sense Classic" theme is selected

##### Actual behavior

The top half of the button is gone

##### Operating system

```
[ x ] Windows
[ ] OSX
[ ] Linux
```
##### Qlik Sense

```
[ x ] Desktop
[ ] Enterprise
```
##### Browser

```
[ ] Chrome
[ ] Firefox
[ ] Internet Explorer
[ ] Edge
[ ] Others: XXX


### Versions

* Extension version: 0.8.3
* Browser: N/A
* Qlik Sense: Nov 2017
* Operating system: Windows 10 Enterprise
* [Other relevant versions]
![2018-01-31_9-11-19](https://user-images.githubusercontent.com/18419897/35609654-d092cd6e-0666-11e8-837f-c41f01a29c8c.png)

**Comment by stefanwalther** [comment]
See #84, not planning to fix this.
