### ISSUE TITLE
Extension doesn't work in Qlik Sense Server

### ISSUE THREAD

**Issue by Julianamia** [stefanwalther/sense-navigation#132]
Hello, 

I use extension in Qlik Sense Desktop but when i try to export extension in Qlik Sense Server, it's doesn't work. 

There is an explication ? 

Thanks you :)

**Comment by stefanwalther** [comment]
Hi, can it be that you ran into the following problem?

https://github.com/stefanwalther/sense-extension-install#i-am-getting-an-error-uploading-the-extension-to-qlik-sense-server-what-can-i-do

I hope this helps, let me know.

**Comment by stefanwalther** [comment]
ping ^ @Julianamia

**Comment by stefanwalther** [comment]
I am closing this for now as I didn't get any answer.

Please feel free to create a new issue or to re-open this issue if the problem still exists based on the v1.0 version (#58 )
