### ISSUE TITLE
Mouseover Navigation Button - remove appearance of  full screen buttons, etc...

### ISSUE THREAD

**Issue by jerryr125** [stefanwalther/sense-navigation#135]
### Description

Is there a way to not display the full screen button, etc... when a user drags the mouse over over the navigation button ??

Current version of Qlik Sense

**Comment by stefanwalther** [comment]
Hi @jerryr125, can you please provide a bit more details:

- Which version of sense-navigation are you using?
- I don't understand why you talk about a "full-screen button", can you provide a screenshot here?

**Comment by jerryr125** [comment]
Hi Stefan - Thanks for the response. We are using RT-18 V1.9.9.3When we go to the RT-Theme 18 and click on the Template Builder.Next, we go to edit the templateid_213599  Top Video Rev Slider we simply get a blank screen that pops up..See attachment - jerry 


-------- Original Message --------
Subject: Re: [stefanwalther/sense-navigation] Mouseover Navigation
Button - remove appearance of full screen buttons, etc... (#135)

**Comment by zwootten** [comment]
@jerryr125 not sure if this is the best way but I removed the button by adding 
`.qv-object-nav.inline{display:none!important}`
to \sense-navigation\lib\css\main.min.css

**Comment by stefanwalther** [comment]
I don't think that this is still an issue with v1.0 of _sense-navigation_, therefore closing this issue.
Thx for filing the issue and pls feel to re-open or create a new one if you continue to experience this behavior.
