### ISSUE TITLE
Pareto Select action;

### ISSUE THREAD

**Issue by sbrusse** [stefanwalther/sense-navigation#137]
This is an enhancement request. I really like the extension, but I'm missing one of the most powerfull action triggers available in Qlikview: Pareto Select.

With this action you can automatically select the customers or product that contribute to 80 percent of turnover. The pareto select actions takes three parameters: 
1. Dimension field
2. Meausure expression
3. Percentage

With these parameters you can calculate the accumulative percentage of total per field value based on the measure expression. The result of the action is a selection of the field values that contribute to N percent of total.

**Comment by stefanwalther** [comment]
Hi @sbrusse, thx for the input. Yes, this is indeed something which could be a very helpful functionality of sense-navigation. I'll look into it.

**Comment by stefanwalther** [comment]
I keep this open for reference, but will not actively work on it.

Please feel free to open a PR (for v1.0 - #58 ), then I am more than happy to have a look at it.

**Comment by stefanwalther** [comment]
Closing as the extension has been "taken over" by Qlik, now part of the [Dashboard Bundle](
https://help.qlik.com/en-US/sense/Subsystems/Hub/Content/Sense_Hub/Visualizations/DashboardBundle/dashboard-bundle.htm), called "Navigation Button Extension".
