### ISSUE TITLE
Unable to display other than General tab for version 1.0x

### ISSUE THREAD

**Issue by analienx** [stefanwalther/sense-navigation#142]
### Description

After dragging the sense-tab object to the sheet only general tab is displayed. Valid for versions 1.0x, version 0.83 works just fine (yet there are security issues so we would like to go with the newest version that does not have the XSS vulnerabilities). 

### Steps to Reproduce

1. Drag the extension to the sheet

##### Expected behavior

See multiple tabs for extension config, not just general

##### Actual behavior
onlgz general tab
##### Operating system

Windows
``
##### Qlik Sense
Desktop
```

##### Browser
Chrome  { notapplicable


### Versions

* Extension version: 1.0xx
* Browser: 
* Qlik Sense:  two versions tried = 3.2.2 and November 17
* Operating system: 
Windows 2007

**Comment by stefanwalther** [comment]
Hi - with "tab" you mean the accordion in the property panel?

**Comment by analienx** [comment]
That is correct.
Also console throws lot of errors

Sent from my Windows 10 phone

________________________________

**Comment by stefanwalther** [comment]
Hi @analienx, it would be very helpful if you could post a screenshot of the errors here (or even better the full text of it)? Thx in advance. Stefan

**Comment by JMHellendoorn** [comment]
![sense-navigation internet explorer 1](https://user-images.githubusercontent.com/33353204/39984213-bbef4b5e-575a-11e8-81dd-cce568618050.png)
Please find attached a screenshot of the issue. I think this issue is the same as request #140. If so, it only happens in Internet Explorer.

**Comment by stefanwalther** [comment]
OK, yes, I definitely need to do some testing on IE ... ;-( ... unfortunately ...

**Comment by stefanwalther** [comment]
Do you have the 0.8x version installed somewhat in parallel, or is it an app where you have used the old version, too?
I am trying to reproduce the issue to be able to fix it.

**Comment by stefanwalther** [comment]
Could you pls open the Chrome Developer Tools Console and show me what's listed there, there must be some errors there I guess ... That would be super-useful.

**Comment by analienx** [comment]
Hello,
That is correct, 0.8x version works without any issues.
I'm afraid we removed the new version and left with the old one instead, let me check if it is on one of our environments

Sent from my emergency iPhone. Please forgive possible misspellings

________________________________

**Comment by stefanwalther** [comment]
So what are you saying? Both versions: v1.x and 0.8x are installed in parallel? How is this even possible? I guess, you are then using Desktop and not server and have just put the extensions side by side in different folders?

**Comment by analienx** [comment]
Hello, firstly there was never version then it was Uninstalled (removed) and replaced with older one. Not at the same time. Enterprise version,not desktop. November 17

Sent from my emergency iPhone. Please forgive possible misspellings

________________________________

**Comment by stefanwalther** [comment]
Hi @analienx, @JMHellendoorn , please try the new RC-03: 

- Direct Download: https://github.com/stefanwalther/sense-navigation/raw/v1.0/build/sense-navigation_v1.0.0-rc-03.zip
- Branch: https://github.com/stefanwalther/sense-navigation/tree/v1.0

I found the error:
- In Qlik Sense Desktop and older browsers (like IE 11) JavaScripts `const` and `let` did not work, which actually broken the extension.
- Fixed that now and tested in
  - Qlik Sense Desktop June 2018 (inside the Desktop, not only using http://localhost:4848)
  - Firefox
  - Chrome
  - Edge

Please give it a try an let me know.
Thx a lot in advance!

**Comment by JMHellendoorn** [comment]
Thanks @stefanwalther 
The solution works now.

**Comment by stefanwalther** [comment]
Great, thx for notifying me.
Then I can close this ... ;-)
