### ISSUE TITLE
Not working on external server in June 2018

### ISSUE THREAD

**Issue by lachlanwwells** [stefanwalther/sense-navigation#146]
### Description

Script error in console, and invalid visualisation is displayed

### Steps to Reproduce

1. Add object to mashup
2. Display mashup on external server

##### Expected behavior

Objects renders correctly

##### Additional info
Please note changes in June 2018 Developer help:
https://help.qlik.com/en-US/sense-developer/June2018/Content/Troubleshooting-developer.htm?_ga=2.122214473.313708261.1530515208-1076293928.1526606904

 "The file in the extension is "styles.css", which will work in a non-cross-site scenario. In a cross-site scenario, RequireJS will look for a "style.css.js" file instead, which typically is not available."

"If you have access to the QMC and can update the extension, wrap the file inside a corresponding js-file. The format required by RequireJS is:

define([], function () { return "the text from the original file";});"

##### Actual behavior

Invalid visualisation is displayed and console errors are logged
![image](https://user-images.githubusercontent.com/26990992/42195697-84cebc24-7ebd-11e8-8a1d-f52c56ee869f.png)

### Environment
Qlik Sense June 2018
##### Operating system

```
[x ] Windows
[ ] OSX
[ ] Linux
```
##### Qlik Sense

```
[ ] Desktop
[x] Enterprise
```

##### Browser

```
[x] Chrome
[ ] Firefox
[ ] Internet Explorer
[ ] Edge
[ ] Others: XXX
```

### Versions

* Extension version:  0.8.3
* Browser: Chrome
* Qlik Sense:  June 18
* Operating system:  Server 2016
* [Other relevant versions]

**Comment by stefanwalther** [comment]
Did you try with the v1.0 version of the extension, which I will release very, very soon?

**Comment by stefanwalther** [comment]
It anyhow delivers so much more functionality and is much more tested, so I highly recommend to move to the v1.0+ branch.

**Comment by stefanwalther** [comment]
Closing as I focus on getting v1.0 of this extension out.
