### ISSUE TITLE
Version 1.0 Beta 10 don't work on Qlik Sense Desktop June 2018

### ISSUE THREAD

**Issue by gersonjunior87** [stefanwalther/sense-navigation#151]
Hi,

I update the extension to the v1.0 (beta 10, the latest version) and the extension don't work.

## Steps to Reproduce

1. I deleted the old extension from the extesion folder (v0.8)
2. I downloaded the new version of the \build folder (beta 10)
3. I created new folder (sense-navigation) in the extesion folder
4. I pasted the files into this folder

## Expected behavior

Update the extesion to explorer the new functions (css color)

## Actual behavior

The options of the extesion didn't show up for me
[See the printscreen](https://preview.ibb.co/mBP0az/extension.png)

## Operating system
[x] Windows 10

## Qlik Sense
[x] Desktop (June 18)

## Browser
[x] Chrome

**Comment by stefanwalther** [comment]
Hmmm, thx for the report, I'll investigate ...

**Comment by stefanwalther** [comment]
Any further hints? Eg. Chrome-Dev-Tools log?

**Comment by gersonjunior87** [comment]
I returned to version 0.8. I'll install v1.0 and the logs to you.

**Comment by stefanwalther** [comment]
^ can you provide any logs, any further details?

BTW, I have just release the release-candidate for v1.0, based on heavy testing, can you try?

Thx in advance for your feedback, which is very appreciated.

**Comment by gersonjunior87** [comment]
@stefanwalther , thank you for your support.

How can i provide logs to you? I don't know.

Anyway, i tried the RC2 and didn't work =/.

**Comment by stefanwalther** [comment]
I have good news ... I am pretty sure, I found the issue ... will publish a new release within a few hours ...

**Comment by stefanwalther** [comment]
Hi @gersonjunior87, please try the new RC-03: 

- Direct Download: https://github.com/stefanwalther/sense-navigation/raw/v1.0/build/sense-navigation_v1.0.0-rc-03.zip
- Branch: https://github.com/stefanwalther/sense-navigation/tree/v1.0

I found the error:
- In Qlik Sense Desktop and older browsers (like IE 11) JavaScripts `const` and `let` did not work, which actually broken the extension.
- Fixed that now and tested in
  - Qlik Sense Desktop June 2018 (inside the Desktop, not only using http://localhost:4848)
  - Firefox
  - Chrome
  - Edge

Please give it a try an let me know.
Thx a lot in advance!

**Comment by gersonjunior87** [comment]
Apparently, worked =)
I'll test more and return.

**Comment by stefanwalther** [comment]
Great, thx a lot for verifying ... I'll close therefore this issue ...
