### ISSUE TITLE
I found this extension very useful. But can 'color by expression' for each measure can be added?

### ISSUE THREAD

**Issue by qliknewuser** [stefanwalther/sense-navigation#161]
I find this extension really useful. But one request: can 'color by expression' field for each measure can be added?

**Comment by stefanwalther** [comment]
How would this be an action? Can you please elaborate, thx.
Are you sure you mean _sense-navigation_?

**Comment by qliknewuser** [comment]
Hi Stefan, Thanks for replying. I was referring to 'Color by expression' condition which is already inbuilt in the Qlik sense Table. If we can get that field in this extension, will be really helpful.

**Comment by stefanwalther** [comment]
@qliknewuser What is the use-case? Coloring the button by expression?

**Comment by qliknewuser** [comment]
Use case for ex. I have 'percentage' column in the table and want to color  fields in that column based on its values ie. if percentage is less than 50%, red else green.

**Comment by stefanwalther** [comment]
Sorry, I still don't get why you want to use the sense-navigation extension to do that. How exactly would that work?

**Comment by qliknewuser** [comment]
I am really sorry. Kindly ignore my request and I will close this issue.
