### ISSUE TITLE
Sample app can't be downloaded

### ISSUE THREAD

**Issue by NooL** [stefanwalther/sense-navigation#163]
## Description

[Description of the issue]
When Download is completed, a window opens with an attempt to open the file
### Steps to Reproduce

1. [Step one]
2. [Step two]
3. ...

#### Expected behavior
just download of the file
[What you expected to happen]

#### Actual behavior

[What actually happened]

[Please include log files (e.g. Qlik Sense Server logs or Chrome Dev Tools' console output to the issue).]

#### Operating system

```
[ ] Windows
[ ] OSX
[ ] Linux
```
#### Qlik Sense

```
[ ] Desktop
[ ] Enterprise
```

#### Browser

```
[ ] Chrome
[ ] Firefox
[ ] Internet Explorer
[ ] Edge
[ ] Others: XXX
```

### Versions

* Extension version: [Version of the extension]
* Browser: 
* Qlik Sense Desktop: [Version of Qlik Sense Desktop]
* Qlik Sense Enterprise: [Version of Qlik Sense Enterprise]
* Operating system: 
* [Other relevant versions]

**Comment by NooL** [comment]
Hi Stefan,

 

Not really..

Still getting this window:



 

Thanks & Regards,

 

Dafna

**Comment by stefanwalther** [comment]
Sorry, I don't see anything in your post above!

**Comment by stefanwalther** [comment]
But in general, this is really not an issue related to sense-navigation, probably something going on with your browser ... try another browser?

**Comment by NooL** [comment]
Hi Stefan,
I've managed to download the app with IE from the link you provided.
(Chrome tries to open the file and downloads fails.)

Thanks!

**Comment by stefanwalther** [comment]
Great, OK, closing this issue.
