### ISSUE TITLE
Download Link Broken for v1.0x Latest

### ISSUE THREAD

**Issue by CryCLL** [stefanwalther/sense-navigation#164]
## Description

Following the link for the latest download... https://github.com/stefanwalther/sense-navigation/raw/v1.0/build/sense-navigation_latest.zip

returns a 404 not found.

#### Operating system

```
[x] Windows
[ ] OSX
[ ] Linux


#### Browser

```
[ x ] Chrome
[ ] Firefox
[ ] Internet Explorer
[ x ] Edge
[ ] Others: XXX
```

**Comment by stefanwalther** [comment]
OK; fixed, thx.
