### ISSUE TITLE
Not working in Qlik Sense Enterprise September 2018

### ISSUE THREAD

**Issue by atomov223** [stefanwalther/sense-navigation#165]
## Description

The extension is not Working on Qlik Sense Enterprise September 2018. 

I tried it first with Qlik Sense Desktop September 2018, and it is working, very beautifully.
#### Expected behavior

When the extension is drag-droped into the sheet, it should show

#### Actual behavior

When the extension is drag-droped into a sheet, nothing happens. 

### Environment
Windows Server 2012
#### Operating system
Windows
#### Qlik Sense

```
[X ] Desktop
[ X] Enterprise
```

#### Browser

```
[ ] Chrome
[ ] Firefox
[X] Internet Explorer
[ ] Edge
[ ] Others: XXX
```

### Versions

* Extension version: 1.0
* Browser: Edge
* Qlik Sense Desktop: [September 2018]
* Qlik Sense Enterprise: [September 2018]
* Operating system: 
* [Other relevant versions]

**Comment by atomov223** [comment]
Okay, so It was not working, because the browser was Internet Explorer v11. 


When I opened it in Chrome, it works. 



But Now I have another issue, 

When I get the extension inside an iFrame object, it doesn't redirect me to sheet, it does nothing. Is this because of the API's concerned when using Iframes?

**Comment by stefanwalther** [comment]
So you are using the extension in a Mashup?

**Comment by stefanwalther** [comment]
Strange regarding IE11, I have tested IE11, will do again ...

**Comment by saikirannama** [comment]
For me also same issue...

In Internet explorer v11 its not working...Its showing an empty page..
even extension object properties also not visible...

Need help immediately...

**Comment by stefanwalther** [comment]
Are you using the extension being downloaded from this page for do you use the bundled extension in the Nov 2018 release?

**Comment by saikirannama** [comment]
Hi Stefan,
Thanks for your reply

I have downloaded the latest extension from build which you have mentioned.
FYI - I'm using qlik sense September 2018 version.

**Comment by venrajah** [comment]
Hi Stefan,

May I know whether we have an update for the reported IE 11 version compatibility issue? Please do let me know if we have any alternate solution for the IE 11 users.

Regards,
Venkat

**Comment by stefanwalther** [comment]
Closing as the extension has been "taken over" by Qlik, first as part of the [Dashboard Bundle](
https://help.qlik.com/en-US/sense/Subsystems/Hub/Content/Sense_Hub/Visualizations/DashboardBundle/dashboard-bundle.htm), called "Navigation Button Extension" and then later on as a native object (https://help.qlik.com/en-US/cloud-services/Subsystems/Hub/Content/Sense_Hub/Visualizations/Button/button.htm).
