### ISSUE TITLE
Cannot display master item description as information for the chart.

### ISSUE THREAD

**Issue by PlexPro** [stefanwalther/sense-navigation#166]
## Description

Cannot display master item description as information for the chart.

### Steps to Reproduce

0. Create a Master Visualization.
1. Under "Master Item Details" add a description.
2. Under "General", turn on "Show details".
3. Close editing, right-click on the button and select "i".

#### Expected behavior

I expected to see the description.  Description, of course, is not an attribute of the non-master-item "sense-navigation", so maybe you didn't program for this.

#### Actual behavior

The details window appears, with nothing in it.

[Please include log files (e.g. Qlik Sense Server logs or Chrome Dev Tools' console output to the issue).]

#### Operating system

```
[ X ] Windows
[ ] OSX
[ ] Linux
```
#### Qlik Sense

```
[ ] Desktop
[ X ] Enterprise
```

#### Browser

```
[ X ] Chrome
[ ] Firefox
[ ] Internet Explorer
[ ] Edge
[ ] Others: XXX
```

### Versions

* Extension version: 1.x (downloaded in mid-October)
* Browser: Chrome Version 69.0.3497.100 (Official Build) (64-bit)
* Qlik Sense Desktop: 
* Qlik Sense Enterprise: June 2018 (12.26.1)
* Operating system: 
* [Other relevant versions]

Let me know if you actually want log files.

**Comment by stefanwalther** [comment]
Closing as the extension has been "taken over" by Qlik, now part of the [Dashboard Bundle](
https://help.qlik.com/en-US/sense/Subsystems/Hub/Content/Sense_Hub/Visualizations/DashboardBundle/dashboard-bundle.htm), called "Navigation Button Extension".
