### ISSUE TITLE
CSS not working

### ISSUE THREAD

**Issue by axana96** [stefanwalther/sense-navigation#167]
Hi,

I want to add custom CSS to the buttons. When I do this it is not working. I also used the example file. The buttons on the button-by-css sheets are working. However, when I add a new button the css is not working to that button.

I am using latest version on qlik sense desktop and qlik sense server

**Comment by tolue** [comment]
I have the same problem. I've copied  a button from the example file in my app. This works.

**Comment by CaroCte** [comment]
Hello I copy/past from the example and like this it works. However the navigation between sheets is not working. Do you now if a new release will be available? 
Thanks

**Comment by stefanwalther** [comment]
Closing as the extension has been "taken over" by Qlik, now part of the [Dashboard Bundle](
https://help.qlik.com/en-US/sense/Subsystems/Hub/Content/Sense_Hub/Visualizations/DashboardBundle/dashboard-bundle.htm), called "Navigation Button Extension".
