### ISSUE TITLE
v1.0.0 does not display extension in IE11 with September 2018 release

### ISSUE THREAD

**Issue by andoryuu1** [stefanwalther/sense-navigation#169]
## Description

Open a sheet in an app with the extension in chrome and it displays no problem.  Open the same sheet in IE11 and the sheet is empty.  Developer tools relay the following errors in IE11, but not in Chrome:

> SCRIPT5007: Unable to get property '__esModule' of undefined or null reference
46.c387b74a431853bfa2cf.js (515,21905)
> 46.c387b74a431853bfa2cf.js (515,21905)

which takes you to a section of [crossroads.js](http://millermedeiros.github.com/crossroads.js/) with the following function:
`function(t){t=t.__esModule&&t.default?t.default:t;e(t)}`

IE11 also specifies syntax error in swr-sense-navigation.js at 11,8157 at this point:
`.field(field).unlock()},wait:function(ms){var waitMs=ms||100;return new qlik.Promise(function(resolve){var wait=setTimeout(()=>{clearTimeout(wait),resolve()},waitMs)})}},$scope.navigationAction={},$scope.firstSheet=function()`

### Steps to Reproduce

1. Open up app in September 2018 Patch 1 version that has a sheet with a navigation button on it in Internet Explorer 11 (my version 11.2665.14393.0).
2. Observe blank space where button should be
3. Open developer tools and see above errors
4. Perform steps in chrome and no errors observed.  Button is present

#### Expected behavior

Button to be present on opening a sheet.  No underlying JS error.

#### Actual behavior

[What actually happened]

IE11 Dev tools:
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
analysis
HTML1300: Navigation occurred.
analysis
SCRIPT5007: Unable to get property '__esModule' of undefined or null reference
46.c387b74a431853bfa2cf.js (515,21905)
SCRIPT5007: Unable to get property '__esModule' of undefined or null reference
46.c387b74a431853bfa2cf.js (515,21905)
SCRIPT5007: Unable to get property '__esModule' of undefined or null reference
46.c387b74a431853bfa2cf.js (515,21905)
SCRIPT5007: Unable to get property '__esModule' of undefined or null reference
46.c387b74a431853bfa2cf.js (515,21905)
SCRIPT1002: Syntax error
swr-sense-navigation.js (11,8157)

Chrome Dev Tools:
/extensions/swr-sense-navigation/lib/external/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0:1 GET https://qlik/extensions/swr-sense-navigation/lib/external/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0 net::ERR_ABORTED 404 (Not Found)

#### Operating system

```
[X ] Windows
[ ] OSX
[ ] Linux
```
#### Qlik Sense

```
[ ] Desktop
[X ] Enterprise
```

#### Browser

```
[X ] Chrome
[ ] Firefox
[X ] Internet Explorer
[ ] Edge
[ ] Others: XXX
```

### Versions

* Extension version: v1.0.0
* Browser: IE 11.2665.14393.0, Chrome  69.0.3497.100
* Qlik Sense Desktop: N/A
* Qlik Sense Enterprise: 12.36.3 (Sep 18 P1)
* Operating system: Windows 10

**Comment by spoorthy111** [comment]
This issue is happening with V0.8 with qliksense 3.2 with ie11.

**Comment by alangrn** [comment]
Hi andoryuu1
Did you get this to work with IE? If so what change did you make?

**Comment by andoryuu1** [comment]
Sadly, no. We had to use 1.0.0-beta-03. Seemed to be the latest version that worked with IE.

**Comment by camara-raf** [comment]
JELZO_NL posted on the Qlik branch page:
"To fix the issue of the extension not working in IE11 (this is due to ES6 Arrow Function syntax not being supported), simply replace this specific text on line 11 in swr-sense-navigation.js:

setTimeout(()=>{clearTimeout(wait),resolve()},waitMs)
With:
setTimeout(function(){clearTimeout(wait);resolve();},waitMs)
"

**Comment by stefanwalther** [comment]
Closing as the extension has been "taken over" by Qlik, first as part of the [Dashboard Bundle](
https://help.qlik.com/en-US/sense/Subsystems/Hub/Content/Sense_Hub/Visualizations/DashboardBundle/dashboard-bundle.htm), called "Navigation Button Extension" and then later on as a native object (https://help.qlik.com/en-US/cloud-services/Subsystems/Hub/Content/Sense_Hub/Visualizations/Button/button.htm).
