### ISSUE TITLE
Sense Bundled Version works on one computer but not on the other - touch screen issue

### ISSUE THREAD

**Issue by dim33** [stefanwalther/sense-navigation#170]
I have Qlik Sense (November 2018 release 12.44.3) installed on my desktop and on my laptop.

On my desktop the extension works as expected however on my laptop it will not work. My laptop is touch screen so I have tried disabling this in Sense but it makes no difference.

The extension has been correctly installed by the Qlik installation process to the correct location. I have also tried copying the extension from the desktop to the laptop but it made no difference.

I am attempting to use the button to navigate to alternative sheets. The extension appears as expected in Sense and can be configured. Nothing happens though when I press the button to navigate to another sheet.

Both computers are running Windows 10 64bit.

Edit: I have just noticed that the extension works on my laptop if I physically touch the button on the screen. However it will not work when I click it with the mouse. Even if I turn off touch in Sense the button still works if I touch it, but again not with a mouse click.

Edit 2: I disabled the touch screen via device manager and confirmed touch not working. Then I reopened Qlik and navigation buttons did respond to the mouse and worked as expected. After re-enabling touch again in device manager the navigation buttons again stopped responding to the mouse. So the issue relates to the touch screen.

**Comment by stefanwalther** [comment]
Closing as the extension has been "taken over" by Qlik, first as part of the [Dashboard Bundle](
https://help.qlik.com/en-US/sense/Subsystems/Hub/Content/Sense_Hub/Visualizations/DashboardBundle/dashboard-bundle.htm), called "Navigation Button Extension" and then later on as a native object (https://help.qlik.com/en-US/cloud-services/Subsystems/Hub/Content/Sense_Hub/Visualizations/Button/button.htm).
