### ISSUE TITLE
Navigation Actions "Add Item" button not working

### ISSUE THREAD

**Issue by bargross** [stefanwalther/sense-navigation#171]
## Description

[Description of the issue]
The navigation and actions settings of the sense extension do not work, basically the add item button is supposed to allow the user to add a custom action but once you press it, it doesn't work, probably due to badly configured properties.

### Steps to Reproduce

1. Open the app
2. drag and drop the extension on the sheet
3. personalize it and try to add an action

#### Expected behavior

Allow me to add an action and personalize it, after that the action should work but that remains to be seeing as I can't even add one thus far.

#### Actual behavior

Nothing happens

#### [Please include log files (e.g. Qlik Sense Server logs or Chrome Dev Tools' console output to the issue).]

Nothing is printed on the console. the only thing that can give you a clue is the fact that the "add item" button of the array property does nothing then you can assume that no action will be triggered, therefore you might see an error on the console log but no errors are thrown thus far.

#### Operating system

Windows7, 10, doesn't matter. It'd probably fail on any.

#### Qlik Sense

```
[x] Desktop
[x] Enterprise
```

#### Browser

```
[x] Chrome
[x] Firefox
[ ] Internet Explorer
[ ] Edge
[ ] Others: XXX
```

### Versions

* Extension version: latest (1.0.0)
* Browser: chrome
* Qlik Sense Desktop: latest (february 2019)
* Qlik Sense Enterprise: latest (february 2019)
* Operating system: Again?
* [Other relevant versions]

**Comment by andu-stan** [comment]
Did anyone manage to fix this issue?

**Comment by stefanwalther** [comment]
Closing as the extension has been "taken over" by Qlik, first as part of the [Dashboard Bundle](
https://help.qlik.com/en-US/sense/Subsystems/Hub/Content/Sense_Hub/Visualizations/DashboardBundle/dashboard-bundle.htm), called "Navigation Button Extension" and then later on as a native object (https://help.qlik.com/en-US/cloud-services/Subsystems/Hub/Content/Sense_Hub/Visualizations/Button/button.htm).
