### ISSUE TITLE
Not working in Qlik Sense Enterprise November 2018 

### ISSUE THREAD

**Issue by rameshguptapr** [stefanwalther/sense-navigation#172]
## Description
Navigation buttons are not working in Nov 2018 Version
[Description of the issue]
Navigation buttons are not showing frequently..
### Steps to Reproduce

1. Login to Hub
2. Navigate to the sheet where the Navigation extension is.
3. It will show as 'Invalid Visualization'

#### Expected behavior
Buttons should be displayed

#### Actual behavior
Buttons are not displayed

### Environment
Production
#### Operating system
Windows

#### Qlik Sense

[ ] Enterprise
```

#### Browser

```
[ ] Chrome
[ ] Firefox
[ ] Internet Explorer
[ ] Edge

**Comment by rameshguptapr** [comment]
Hi There,

Greetings!!
This is a very useful extension in our reports, which we are using in most of the reports.
Now we are facing issue mean, Button will not displayed most of the times instead it is displayed as 'invalid visualization' - Error.

Please help us here in getting it rectified.
feel free to reach me at rameshguptapr78@gmail.com

Thanks & Regards,
Ramesh

**Comment by stefanwalther** [comment]
Closing as the extension has been "taken over" by Qlik, first as part of the [Dashboard Bundle](
https://help.qlik.com/en-US/sense/Subsystems/Hub/Content/Sense_Hub/Visualizations/DashboardBundle/dashboard-bundle.htm), called "Navigation Button Extension" and then later on as a native object (https://help.qlik.com/en-US/cloud-services/Subsystems/Hub/Content/Sense_Hub/Visualizations/Button/button.htm).
