### ISSUE TITLE
The extension is not working on QlikSense Desktop November 2018 patch 2

### ISSUE THREAD

**Issue by chonnathan** [stefanwalther/sense-navigation#173]
## Description

The extension is not working on QlikSense November 2018 Patch 2.
(Action and extension property is not active)

### Steps to Reproduce

1. Open QlikSense desktop
2. Open application
3. Go to Edit
4. Drag the extension object to the design area
5. The properties on the right pane cannot edit/adjust

#### Operating system

```
[ X] Windows
[ ] OSX
[ ] Linux
```
#### Qlik Sense

[X ] Desktop
[ ] Enterprise
```

#### Browser

[ ] Chrome
[ ] Firefox
[X ] Internet Explorer
[ ] Edge
[ ] Others: XXX
```

### Versions

* Extension version: v1.0 - Alpha
* Browser: 11
* Qlik Sense Desktop: Qlik Sense Desktop November 2018 Patch 2 (12.44.3)
* Operating system: WINDOW 10
* [Other relevant versions]

**Comment by amien90** [comment]
same here .. any solution?

**Comment by amien90** [comment]
btw .. . bundle version works .. community version doesn't work

**Comment by stefanwalther** [comment]
Closing as the extension has been "taken over" by Qlik, first as part of the [Dashboard Bundle](
https://help.qlik.com/en-US/sense/Subsystems/Hub/Content/Sense_Hub/Visualizations/DashboardBundle/dashboard-bundle.htm), called "Navigation Button Extension" and then later on as a native object (https://help.qlik.com/en-US/cloud-services/Subsystems/Hub/Content/Sense_Hub/Visualizations/Button/button.htm).
