### ISSUE TITLE
Mailto not working

### ISSUE THREAD

**Issue by BennyBigData** [stefanwalther/sense-navigation#174]
## Description

Trying to use the button to start an email. When configuring the navigation to Open a website/eMail and inserting an email address "Johndoe@gmail.com", clicking on the link will make you browse to "gmail.com". Everything before and including the @ seems to be dropped. 

### Steps to Reproduce

1. Create button
2. Set navigation behaviour to Open a website/eMail
3. insert eMail address in the "website" field. 
4. close edit mode and click the button. 

#### Expected behavior

Open new email in standard email client to the inserted address. 

#### Actual behavior

A new tab is opened in your browser, pointing to the email domain only. 

#### Operating system

```
[x ] Windows
[ ] OSX
[ ] Linux
```
#### Qlik Sense
Qlik Sense 2018 September

[ ] Desktop
[x ] Enterprise
```

#### Browser

```
[x ] Chrome
[ ] Firefox
[ ] Internet Explorer
[ ] Edge
[ ] Others: XXX
```


### Versions

* Extension version: v1.0.0
* Browser: 
* Qlik Sense Desktop: [Version of Qlik Sense Desktop]
* Qlik Sense Enterprise: September 2018
* Operating system: 
* [Other relevant versions]

**Comment by stefanwalther** [comment]
Closing as the extension has been "taken over" by Qlik, first as part of the [Dashboard Bundle](
https://help.qlik.com/en-US/sense/Subsystems/Hub/Content/Sense_Hub/Visualizations/DashboardBundle/dashboard-bundle.htm), called "Navigation Button Extension" and then later on as a native object (https://help.qlik.com/en-US/cloud-services/Subsystems/Hub/Content/Sense_Hub/Visualizations/Button/button.htm).
