### ISSUE TITLE
Extension not working in Single Navigator 

### ISSUE THREAD

**Issue by inkkumar3** [stefanwalther/sense-navigation#175]
## Description

Hi,
This navigation buttons works only in Qliksense when i use <http(s)://<qliksenseurl/sense/app/....

this does not work when i used <http(s)://<qliksenseurl>/single/?appid=124356

### Steps to Reproduce

1. Create an App and add "Sheet Navigation and actions" to the App
 2. in Navigation behaviour , provide  options of "Next sheet" or "First sheet" or any sheets other than url  
3. The navigation works without issues on clicking done
4. Open <http(s)://<qliksenseurl/>dev-hub
5. Select single configurator and select newly created app 
6. Copy the link or click on view to open in new window
7. The link does not open and not throw any error 

#### Expected behavior

[What you expected to happen]

#### Actual behavior

[What actually happened]

[Please include log files (e.g. Qlik Sense Server logs or Chrome Dev Tools' console output to the issue).]

#### Operating system

```
[ ] Windows
[ ] OSX
[ ] Linux
```
#### Qlik Sense

```
[ ] Desktop
[ ] Enterprise
```

#### Browser

```
[ ] Chrome
[ ] Firefox
[ ] Internet Explorer
[ ] Edge
[ ] Others: XXX
```

### Versions

* Extension version: [Version of the extension]
* Browser: 
* Qlik Sense Desktop: [Version of Qlik Sense Desktop]
* Qlik Sense Enterprise: [Version of Qlik Sense Enterprise]
* Operating system: 
* [Other relevant versions]

**Comment by stefanwalther** [comment]
Closing as the extension has been "taken over" by Qlik, first as part of the [Dashboard Bundle](
https://help.qlik.com/en-US/sense/Subsystems/Hub/Content/Sense_Hub/Visualizations/DashboardBundle/dashboard-bundle.htm), called "Navigation Button Extension" and then later on as a native object (https://help.qlik.com/en-US/cloud-services/Subsystems/Hub/Content/Sense_Hub/Visualizations/Button/button.htm).
