### ISSUE TITLE
Making the cells in table clickable

### ISSUE THREAD

**Issue by MayankMakes** [stefanwalther/sense-navigation#176]
I ahd developed a table like you said, but now I wanted to apply drill downs to every cell and also make the cells clickable.
How to achieve this?
Drill Down on clickable cells

**Comment by stefanwalther** [comment]
Closing as the extension has been "taken over" by Qlik, first as part of the [Dashboard Bundle](
https://help.qlik.com/en-US/sense/Subsystems/Hub/Content/Sense_Hub/Visualizations/DashboardBundle/dashboard-bundle.htm), called "Navigation Button Extension" and then later on as a native object (https://help.qlik.com/en-US/cloud-services/Subsystems/Hub/Content/Sense_Hub/Visualizations/Button/button.htm).
