### ISSUE TITLE
wrap text in cells and headers

### ISSUE THREAD

**Issue by aabhishekdata** [stefanwalther/sense-navigation#177]
Hi,

How to wrap text in a cell and cell header? Otherwise the column becomes too long and scrolling is not an optimal solution.

Thanks,
Abhishek

**Comment by stefanwalther** [comment]
Closing as the extension has been "taken over" by Qlik, first as part of the [Dashboard Bundle](
https://help.qlik.com/en-US/sense/Subsystems/Hub/Content/Sense_Hub/Visualizations/DashboardBundle/dashboard-bundle.htm), called "Navigation Button Extension" and then later on as a native object (https://help.qlik.com/en-US/cloud-services/Subsystems/Hub/Content/Sense_Hub/Visualizations/Button/button.htm).
