### ISSUE TITLE
Button Layout by CSS not working

### ISSUE THREAD

**Issue by makpolidoru** [stefanwalther/sense-navigation#178]
## Description

Cannot perform customization by CSS or Expression in Version Sep 19, neither in June 19.

### Steps to Reproduce

1. Button Layout
2. Style
3. Custom (by CSS)

#### Expected behavior

Applying the given example :

```
='background-image: 
    linear-gradient(to right, 
        #f6d365 0%, 
        #fda085 51%, 
        #f6d365 100%); 
  color: white; font-weight:bold'
```

I would expect the orange gradient button

#### Actual behavior

Nothing. 

#### Operating system

```
[ x ] Windows
[ ] OSX
[ ] Linux
```
#### Qlik Sense

```
[ x ] Desktop
[ x ] Enterprise
```

#### Browser

```
[ x  ] Chrome
[ ] Firefox
[ ] Internet Explorer
[ ] Edge
[ ] Others: XXX
```

### Versions

* Extension version: [1.0.0]
* Browser: [77.0.3865.120]
* Qlik Sense Desktop: [June 2019]
* Qlik Sense Enterprise: [September 2019]
* Operating system: [Windows 10 Pro 1903]

**Comment by cmpark87** [comment]
I am also not able to get the button to display properly using the CSS method. Are there any updates to make this work.

**Comment by yay1406** [comment]
I have the same problem in Qlik Sense November 2021. But may be, I found a solution: copy/paste the necessary button from the sample application (https://github.com/stefanwalther/sense-navigation/tree/master/example) and it will be working properly in your application!
This is very strange. And it's very sorry, that the problem hasn't solved from 2019.

**Comment by stefanwalther** [comment]
Closing as the extension has been "taken over" by Qlik, first as part of the [Dashboard Bundle](
https://help.qlik.com/en-US/sense/Subsystems/Hub/Content/Sense_Hub/Visualizations/DashboardBundle/dashboard-bundle.htm), called "Navigation Button Extension" and then later on as a native object (https://help.qlik.com/en-US/cloud-services/Subsystems/Hub/Content/Sense_Hub/Visualizations/Button/button.htm).
