### ISSUE TITLE
Icon Not Showing 

### ISSUE THREAD

**Issue by GavinMaree** [stefanwalther/sense-navigation#179]
Upgraded from Qlik Sense June 2019 to September 2019.

I use an icon to indicate an active button

As in June 2019 Native Desktop
![image](https://user-images.githubusercontent.com/41905487/67755693-3f1a0980-fa41-11e9-9ca5-89b9f1720542.png)

As in Sep 2019 Native Desktop
![image](https://user-images.githubusercontent.com/41905487/67756078-075f9180-fa42-11e9-91df-caf61fa214f1.png)

As in Chrome Browser
![image](https://user-images.githubusercontent.com/41905487/67756226-44c41f00-fa42-11e9-8c1f-e1c7c700c80a.png)

![image](https://user-images.githubusercontent.com/41905487/67756160-2827e700-fa42-11e9-881a-4ab431bd78a1.png)

Since the upgrade the icon no longer shows

#### Operating system

[ x ] Windows 10 Pro

#### Qlik Sense

[ x ] Desktop

#### Browser

[ x ] Chrome

### Versions

* Extension version: [Version of the extension]
![image](https://user-images.githubusercontent.com/41905487/67758046-98843780-fa45-11e9-93d2-c7c2ba84577d.png)

Please assist

**Comment by GavinMaree** [comment]
In the interim, I have reinstalled June 2019 and all is well.

**Comment by stefanwalther** [comment]
Why don't you use the bundled extension? Qlik has officially bundled this extension and is from now on supporting it.

**Comment by johncloey** [comment]
I am experiencing the same issue reported by GavinMaree using v0.8 of your extension. If I upgrade to v1.0 of your extension I can reconfigure to display the extension as a navigation link with icon. The bundled extension doesn't appear to support the Link style that your original extension has.

**Comment by stefanwalther** [comment]
Closing as the extension has been "taken over" by Qlik, first as part of the [Dashboard Bundle](
https://help.qlik.com/en-US/sense/Subsystems/Hub/Content/Sense_Hub/Visualizations/DashboardBundle/dashboard-bundle.htm), called "Navigation Button Extension" and then later on as a native object (https://help.qlik.com/en-US/cloud-services/Subsystems/Hub/Content/Sense_Hub/Visualizations/Button/button.htm).
