### ISSUE TITLE
Drop down arrow missing and wrap charcters in the App in September 2019 version

### ISSUE THREAD

**Issue by enpradeepkumar** [stefanwalther/sense-navigation#180]
## Description
Drop down arrow missing and wrap characters in September 2019 version
[Description of the issue]
Drop down arrow is missing
### Steps to Reproduce

1. [Step one]
2. [Step two]
3. ...

#### Expected behavior

[What you expected to happen]
User should get the Drop down arrow to appear for the apps to nvaigate and select the object 
#### Actual behavior

[What actually happened]
Some Wrap characters in the place of drop down arrow.
[Please include log files (e.g. Qlik Sense Server logs or Chrome Dev Tools' console output to the issue).]

### Environment
QlikSense September 2019 Version
#### Operating system
2016 windows
```
[x ] Windows
[ ] OSX
[ ] Linux
```
#### Qlik Sense
September 2019
```
[ ] Desktop
[x ] Enterprise
```

#### Browser
Chrome
```
[x ] Chrome
[ ] Firefox
[ ] Internet Explorer
[ ] Edge
[ ] Others: XXX
```

### Versions

* Extension version: [Version of the extension]
swr-sense-navigation
* Browser: Chrome
* Qlik Sense Desktop: [Version of Qlik Sense Desktop]
* Qlik Sense Enterprise: [Sep 2019]
* Operating system: 
* [Other relevant versions]

**Comment by stefanwalther** [comment]
Closing as the extension has been "taken over" by Qlik, first as part of the [Dashboard Bundle](
https://help.qlik.com/en-US/sense/Subsystems/Hub/Content/Sense_Hub/Visualizations/DashboardBundle/dashboard-bundle.htm), called "Navigation Button Extension" and then later on as a native object (https://help.qlik.com/en-US/cloud-services/Subsystems/Hub/Content/Sense_Hub/Visualizations/Button/button.htm).
