### ISSUE TITLE
Add Reload App action ?

### ISSUE THREAD

**Issue by FulvioBios** [stefanwalther/sense-navigation#181]
HyStefan,

if i may…

about your qsense extension. Is it possibile ADD a ‘Reload app’ action to your button’s actions ?

i’m sorry but  i am a very beginner in qsense 😊

Thank you

 

Fulvio

**Comment by stefanwalther** [comment]
Closing as the extension has been "taken over" by Qlik, first as part of the [Dashboard Bundle](
https://help.qlik.com/en-US/sense/Subsystems/Hub/Content/Sense_Hub/Visualizations/DashboardBundle/dashboard-bundle.htm), called "Navigation Button Extension" and then later on as a native object (https://help.qlik.com/en-US/cloud-services/Subsystems/Hub/Content/Sense_Hub/Visualizations/Button/button.htm).
