### ISSUE TITLE
Action does not work in Alternate States

### ISSUE THREAD

**Issue by horrypong** [stefanwalther/sense-navigation#182]
Really like this extension and many thanks for the efforts. 

I notice one issue when I apply this extension in my dashboard. The extension works very well under default state (e.g. It can select values, clear selection, etc, correctly). However when I apply this extension to a sheet which is set with an alternate state, those actions do not work. For instance it cannot clear any field selections which are made in alternate state, nor can I select any values in those states. I only tested on these two actions but possibly other actions of the extension do not work. 
I have tried setting the state of the sense-navigation to be the same state as the sheet, still it does not work.  

It will be great if this issue can be solved. Many thanks.

### Environment
[X ] Windows

#### Qlik Sense
[X ] Enterprise

#### Browser
[X ] Chrome
[X] Firefox

### Versions

* Extension version: [Version of the extension]
* Browser: 
* Qlik Sense Enterprise: 13.82.4
* Operating system: Windows 10

**Comment by stefanwalther** [comment]
Closing as the extension has been "taken over" by Qlik, first as part of the [Dashboard Bundle](
https://help.qlik.com/en-US/sense/Subsystems/Hub/Content/Sense_Hub/Visualizations/DashboardBundle/dashboard-bundle.htm), called "Navigation Button Extension" and then later on as a native object (https://help.qlik.com/en-US/cloud-services/Subsystems/Hub/Content/Sense_Hub/Visualizations/Button/button.htm).
