### ISSUE TITLE
Could you add an action to create a bookmark and save it (without displaying it), and another action to apply the bookmark later?

### ISSUE THREAD

**Issue by lingzhang8888** [stefanwalther/sense-navigation#184]
## Description

[Description of the issue]

### Steps to Reproduce

1. [Step one]
2. [Step two]
3. ...

#### Expected behavior

[What you expected to happen]

#### Actual behavior

[What actually happened]

[Please include log files (e.g. Qlik Sense Server logs or Chrome Dev Tools' console output to the issue).]

#### Operating system

```
[ ] Windows
[ ] OSX
[ ] Linux
```
#### Qlik Sense

```
[ ] Desktop
[ ] Enterprise
```

#### Browser

```
[ ] Chrome
[ ] Firefox
[ ] Internet Explorer
[ ] Edge
[ ] Others: XXX
```

### Versions

* Extension version: [Version of the extension]
* Browser: 
* Qlik Sense Desktop: [Version of Qlik Sense Desktop]
* Qlik Sense Enterprise: [Version of Qlik Sense Enterprise]
* Operating system: 
* [Other relevant versions]

**Comment by stefanwalther** [comment]
#Closing as the extension has been "taken over" by Qlik, first as part of the [Dashboard Bundle](
https://help.qlik.com/en-US/sense/Subsystems/Hub/Content/Sense_Hub/Visualizations/DashboardBundle/dashboard-bundle.htm), called "Navigation Button Extension" and then later on as a native object (https://help.qlik.com/en-US/cloud-services/Subsystems/Hub/Content/Sense_Hub/Visualizations/Button/button.htm).
