### ISSUE TITLE
Does not install on Sense 2.1.1

### ISSUE THREAD

**Issue by mountaindude** [stefanwalther/sense-navigation#20]
There has been talk elsewhere about some bug causing import (into Sense server) of some extensions to fail, something about the extension ZIP file must not contain any .md files...?
I have failed to get an conclusive description of the bug, I have just noted in several cases that if I create my own extension from scratch on the server, then copy-paste the source code from the downloaded ZIP into my own extension, it works just fine. 
So it's something about the packaging of the ZIP, it seems.

**Comment by stefanwalther** [comment]
Hi,

what have you downloaded? If you download the entire GitHub project it will not work. Goto to the folder "build", there you will fine pre-built .zip packages which are also tested in Qlik Sense 2.1.1 (there is also a link in the README.md directly pointing to the lastest build).

Hope this helps.

**Comment by mountaindude** [comment]
Yes I noticed the build directory, but uploading the sense-navigation_latest.zip file from there fails. 
Having a 3-node 2.1.1 setup, and I have tried uploading on both rim nodes and central node.

**Comment by mountaindude** [comment]
Very odd indeed. As a general cleanup task I removed all mashups created from /dev-hub, and then the extension installed just fine.... Weird. Like the repository was in some not-so-good state after creation those mashups.

**Comment by stefanwalther** [comment]
Closing, since this cannot be reproduced. Please feel free to re-open if you have more info which could help - but most likely not related to this but another extension.
