### ISSUE TITLE
Lock All action

### ISSUE THREAD

**Issue by stefanwalther** [stefanwalther/sense-navigation#22]

**Comment by ziadsa** [comment]
Hi Stefan!

Have you added "lock all" to the extension? I have download the last version of it but I could not find lock all action.

Much Thanks!
Ziad

**Comment by stefanwalther** [comment]
Not yet, but soon ... working on it.

**Comment by stefanwalther** [comment]
Will be added with v0.7.0, uploading soon, you can have a look at it in the branch v0.7.0.
