### ISSUE TITLE
Cannot launch sense-navigation (lgdrazil from branch.qlik.com)

### ISSUE THREAD

**Issue by stefanwalther** [stefanwalther/sense-navigation#23]
> Hi Stefan, good work you've done so far!!! I got a problem with your extension, i can't get my button colored. Using Sense Desktop 2.1.1 and tried in Chrome and the internal Chromium Browser. But it isn't working for me.
> If you need something from me tell me!
> Regards Chris

Hmmm, I cannot reproduce this behavior, can you please ellaborate a bit. What exactly is happening?

* Do you see the extension sense-navigation in the list of extensions?
* Can you drag & drop it into a sheet?
* What's happening then?
* Can you provide a screenshot?
* etc.

Regards
Stefan

**Comment by Chricky** [comment]
Hi Stefan, so here i am! I can Launch the extension and the things i've tested so far are working. The only thing that doesn't work is the coloring. 
![image](https://cloud.githubusercontent.com/assets/12136269/10657935/39da1580-7892-11e5-979f-c5bf192347dd.png)

The linking for example next sheet and so on are working as far as i tested it. I will check out the rest of the functions and come back to you!

Regards
Chris

**Comment by Chricky** [comment]
Another thing that attracted my attention is that if i make the buttons small in editing mode (1x3 Quarters), i'm activating the button when i try to click on it even in editing mode. Is it possible to disable this behavior? it's annoying to you switch sheet if you just want to select it.

**Comment by stefanwalther** [comment]
@Chricky: I have created a separate issue for the "Behavior in Edit mode" => #26

**Comment by stefanwalther** [comment]
Closing, since I could never reproduce it. Feel free to open again, if you can help me to reproduce the issue described above.
