### ISSUE TITLE
Select in Field action and expression editor

### ISSUE THREAD

**Issue by mhr2015** [stefanwalther/sense-navigation#25]
when using the expression editor to select the field name to make a selection via action, the field name appears as =<fieldname> which doesn't work due to the equal sign. In addition, an example on how to choose multiple values form a field via action would be helpful.

**Comment by stefanwalther** [comment]
Which version of Qlik Sense are you using?

**Comment by mhr2015** [comment]
It was 2.1.1

**Comment by stefanwalther** [comment]
Hmm, re-thinking of the solution, I think it would be much better to change this to be a dropdown to select from all existing fields. Doesn't need to be that dynamic that defining a field by using an expression would really help.
What do you think?

**Comment by mhr2015** [comment]
Hi Stefan,

 

yup, a dropdown menu to select dimensions would be ideal and more straight-forward than having to open the expression editor to do that!

 

Cheers,

Matthias

 

Von: Stefan Walther [mailto:notifications@github.com] 
Gesendet: Montag, 2. November 2015 21:51
An: stefanwalther/sense-navigation <sense-navigation@noreply.github.com>
Cc: mhr2015 <mherkommer@gmx.de>
Betreff: Re: [sense-navigation] Select in Field action and expression editor (#25)

 

Hmm, re-thinking of the solution, I think it would be much better to change this to be a dropdown to select from all existing fields. Doesn't need to be that dynamic that defining a field by using an expression would really help.
What do you think?

**Comment by stefanwalther** [comment]
OK, will go for that - I think that's better anyhow.

**Comment by stefanwalther** [comment]
I revised my opinion, for now I think this would over-complicate the UI, but added it to the list of potential improvements on README.md

Closing for now, since this is not an issue but an enhancement.

**Comment by anghelf** [comment]
Hi Stefan, I tried to use this functionality by adding as Field an expression, for example               
if(Field=valuefied,1,0) and as Value 1 and this should work as a filter on the Field with the valuefield, but it didn't work. Is this possible? (since I want to use much more complicated expressions)

**Comment by stefanwalther** [comment]
See #106 Isn't this exactly the same issue?
