### ISSUE TITLE
New feature: Add conditional styling to buttons

### ISSUE THREAD

**Issue by veglar** [stefanwalther/sense-navigation#27]
I would love to see conditional styling/coloring on the buttons. 
IF (Condition = true(), 'styleA', 'StyleB')

**Comment by stefanwalther** [comment]
Interesting request, I'll think of it. But I will probably want to bring this approach into all my visualization extensions ;-)

**Comment by veglar** [comment]
Glad you liked it. 

It is especially handy in Sense where you can´t put two object on top of each-other, as in QlikView, and control the presentation with show conditions.

**Comment by stefanwalther** [comment]
Some use case here: https://www.quickintelligence.co.uk/toggle-buttons-qlik-sense/

**Comment by stefanwalther** [comment]
See #121

**Comment by stefanwalther** [comment]
@veglar: Closed (for branch v1.0, see #58 ) with #122.
