### ISSUE TITLE
Using Button for a URL

### ISSUE THREAD

**Issue by Chricky** [stefanwalther/sense-navigation#28]
Hi Stefan,

i'm trying to use your Button to URL feature, but i can't put "https://" in front of the URL!
As soon as i remove this part it works. I don't know if you wanna look at this, but this is what I noticed.

Regards
Chris

**Comment by stefanwalther** [comment]
Thx for reporting, I will investigate ASAP.

**Comment by stefanwalther** [comment]
Fixed in v.0.5.7
