### ISSUE TITLE
Jump Back Button Function

### ISSUE THREAD

**Issue by Chricky** [stefanwalther/sense-navigation#29]
Hi Stefan,

it would be awesome when there would be any kind of saving the last sheet i was on. So my idea is, when i use these buttons from sheet number 28 for example and jump to sheet one (because this is my filter panel sheet), i need a way to get back to this specific sheet. I'm doing this via If-clause at the moment, but this isn't neat at all (and a lot of work too).

Regards
Chris

**Comment by stefanwalther** [comment]
What's about setting a value to a variable?

**Comment by Chricky** [comment]
So how would i do that? When i'm trying to go back, i don't see a way to give the button that information what specific sheet it has to bring me to

**Comment by stefanwalther** [comment]
Sorry - first for coming back so late, second, yes: this is not possible right now, but quite easy to change ... you still need this?

**Comment by Jatin-Kakani** [comment]
Hi Stefan, 
First of all, the extension is really nice and cool,
I'd also love to see the feature where we can go back to the sheet that brought us.
I am planning to use this extension for one of my projects where I have a requirement to go back to the  original sheet.

Regards,
Jatin

**Comment by stefanwalther** [comment]
OK, I have implemented this in v0.7.0 (will be uploaded soon).

- Added a new navigation action to go to a specific sheet by id. The id can be fetched from a variable
- So the flow would be:
- From sheet1 you set the variable `vSheet` and jump to any sheet (e.g. sheet2)
![image](https://cloud.githubusercontent.com/assets/669728/16857439/066a4516-4a20-11e6-8544-1a8821a4705d.png)

- On sheet2 you just have to add another button and then you jump back to the sheet defined in the variable `vSheet`

![image](https://cloud.githubusercontent.com/assets/669728/16857466/29be3374-4a20-11e6-94d1-344f056cd14c.png)

Closing this thread, feel free to re-open if it doesn't work as expected.

**Comment by pronkrcgj** [comment]
Hi ,

How can i get/save the sheet id?
