### ISSUE TITLE
Go to sheet not working

### ISSUE THREAD

**Issue by ZanEErazz** [stefanwalther/sense-navigation#30]
HI, 

Thanks for this awesome extension. I have created a few buttons. When selecting to navigate to a web site it works BEAUTIFULLY, however it doesn't want to work when selecting the action to go to prev/next or specific sheet.

I am working on Sense Server in the Hub. Is there something I should set up or check before this will work?

**Comment by stefanwalther** [comment]
Thx for reporting this issue!

I assume that you work on Qlik Sense Server 2.1.1, and at the same time gotoSheet is working nicely in Qlik Sense Desktop, right?
A few days I have realized that there is a bug in the Capability API / Navigation API, which we will have to fix in the product. This is depending on the security settings on the server. We will have to investigate a bit more, then I can tell you if there is a workaround or if I can fix this in the extension or not.

**Comment by stefanwalther** [comment]
Potential duplicate: #32

**Comment by stefanwalther** [comment]
This has been fixed in Qlik Sense 2.2, so closing.
