### ISSUE TITLE
Clear selection in Field and Select in field does not seem to work for me!

### ISSUE THREAD

**Issue by nakulnavre** [stefanwalther/sense-navigation#31]
Hello Stefan,
First of all Thank you for creating this extension object. Using this I may be able to achieve a part of my requirement. I am using QlikSense Desktop 2.1.1 and this 'sense-navigation' works perfect for activating specific sheets. I am having trouble in getting the clear selection in field and select in field to work. Its a simple string that I want to be able to select and remove.  The field name comes with a = sign and the value text box just has the string (eg:  ATL). What am I missing?

Regards
Nakul

**Comment by stefanwalther** [comment]
Hi, first sorry for coming back so late to you.
Can you post more details? I have just tested it and it work nicely for me:

![image](https://cloud.githubusercontent.com/assets/669728/13620203/53f6f384-e58e-11e5-9568-cdd2e45af2a2.png)


Regards
Stefan

**Comment by stefanwalther** [comment]
Closing, not received any answer.
