### ISSUE TITLE
Extension not working as expected in QlikSense platform (server)

### ISSUE THREAD

**Issue by nakulnavre** [stefanwalther/sense-navigation#32]
I am able to use this extension on my QS desktop. However when imported to the server, the functionality (buttons) do not work. QlikSense suggest to check some logs. Will gather more information. Could you please confirm if this extension is available for server ?

Thanks
Nakul Navre

**Comment by stefanwalther** [comment]
Thx for reporting. See #30 
Since this is a duplicate, I'll close it.

**Comment by stefanwalther** [comment]
Thx for reporting this issue.
A few days I have realized that there is a bug in the Capability API / Navigation API, which we will have to fix in the product. This is depending on the security settings on the server. We will have to investigate a bit more, then I can tell you if there is a workaround or if I can fix this in the extension or not.

**Comment by stefanwalther** [comment]
Closing, since this has been fixed in Qlik Sense 2.2
