### ISSUE TITLE
Request: How to align the button Label text as : left

### ISSUE THREAD

**Issue by nakulnavre** [stefanwalther/sense-navigation#34]
Hi Stefan,

I am using this extension in one of my dashboard and want to achieve this:-

-- When Button width is set to "Full Width" , I want the lable text to be aligned to left (instead of center as it is now).

Could you please point me to the .css and/or .js  file I must update?

Thanks
Nakul Navre

**Comment by stefanwalther** [comment]
Hi, thx for reporting it, I'll have a look at it.

**Comment by stefanwalther** [comment]
You'll find the code in `.src/swr-sense-navigation.js` (line 47).
I am closing this thread as I am not planning to implement this functionality.
