### ISSUE TITLE
Sheet Navigation Action: Open File

### ISSUE THREAD

**Issue by Chricky** [stefanwalther/sense-navigation#36]
Hi Stefan,
how about another Navigation Action Option for opening local files via a local link (something like "C:\Data\test.txt"). Would be pretty nice to open pdf files or jpg or even programs from qlik.

Regards
Chris

**Comment by stefanwalther** [comment]
So in general opening a local file from within a web application is not a good idea and most of the time even not allowed from a security perspective.
But what I can think of is linking to an object in the media library, then it would also work in a server scenario.

**Comment by stefanwalther** [comment]
Hi,

I tried to implement, but it does never work reliably, always running into security issues on several browsers, read here:

http://arstechnica.com/civis/viewtopic.php?t=1250955
http://stackoverflow.com/questions/2148584/open-a-direct-file-on-the-hard-drive-from-firefox-file

So I have decided to not implementing this "feature", but I am absolutely happy to accept a pull request if you manage to get it working.

Regards
Stefan
