### ISSUE TITLE
Open File

### ISSUE THREAD

**Issue by MarkusPaulhart** [stefanwalther/sense-navigation#40]
It would be great to open a file from a fileshare additionaly to the navigation action "open website".

I tried to use "file:///" (at this option) but that was not working. The extension still creates a link like: "http://file///" and this does not compute. 

So this feature would be great. THX

**Comment by stefanwalther** [comment]
Hi,

I tried to implement, but it does never work reliably, always running into security issues on several browsers, read here:

http://arstechnica.com/civis/viewtopic.php?t=1250955
http://stackoverflow.com/questions/2148584/open-a-direct-file-on-the-hard-drive-from-firefox-file

So I have decided to not implementing this "feature", but I am absolutely happy to accept a pull request if you manage to get it working.

Regards
Stefan
