### ISSUE TITLE
Virtual Proxy

### ISSUE THREAD

**Issue by stefanwalther** [stefanwalther/sense-navigation#44]
Just heard that there are problems with sense-navigation in combination with using a virtual proxy, more details to be added.

**Comment by aihazm** [comment]
It think it's a simple fix (in swr-sense-navigation.js): by using relative path:
```javascript
var faUrl = '/extensions/swr-sense-navigation/lib/external/fontawesome/css/font-awesome.min.css';
```
should be 
```javascript
var faUrl = 'lib/external/fontawesome/css/font-awesome.min.css';
```

**Comment by stefanwalther** [comment]
Thx, that's an easy fix then ;-)
