### ISSUE TITLE
Selecting multiple values in a field

### ISSUE THREAD

**Issue by clarelam** [stefanwalther/sense-navigation#45]
Hi Stefan,

Thanks for creating this extension! However, I can't seem to get the button to select multiple values in a field. Selecting 1 value and clearing selections works fine. I'm working with QS Desktop 2.2

![image](https://cloud.githubusercontent.com/assets/1752113/13730018/ec65f66a-e93a-11e5-8138-2590f1b2a153.png)

Thanks,
Clare

**Comment by stefanwalther** [comment]
Hi @clarelam, thx for reporting, I'll have a look into it.

Regards
Stefan

**Comment by stefanwalther** [comment]
Thx for reporting again, fixed in the newest version 0.5.14
