### ISSUE TITLE
Navigation "tile"

### ISSUE THREAD

**Issue by Sjorsdekwa** [stefanwalther/sense-navigation#46]
Hi Stefan,

The navigation button has almost everything I need, nice work! Except, I would like to be able to adjust the size of the button to create a huge tile. Now it's only possible to adjust the width, but I would also like to adjust the hight. This way I would be able to create a dashboard with a couple of huge tiles that let you navigate to specific sheets. 

Also I would be nice if you could add images instead of colors!

![22 mrt 2016 01-10-36](https://cloud.githubusercontent.com/assets/18006441/13951180/8c5df3de-f02f-11e5-99b6-a01fae052da0.png)

Thanks,
Sjors

**Comment by stefanwalther** [comment]
I think that's a good fit for the Widget concept in Qlik Sense 3.0 ;-)

**Comment by stefanwalther** [comment]
Definitely more appropriate for Widget in 3.0, stay tuned. Therefore closing this issue. Hope this is fine for you.
