### ISSUE TITLE
Creating hover drop down menus

### ISSUE THREAD

**Issue by Simo20091993** [stefanwalther/sense-navigation#47]
Hi Stephan,

Just wondering if it would be possible to allow the creation of hover-dropdown menus in this extension.  Really love this extension and use it a lot.

**Comment by stefanwalther** [comment]
Sounds that this is something you would probably better achieve with a custom visualization extension (see http://branch.qlik.com) or by using the Widget concept in Qlik Sense 3.0

**Comment by stefanwalther** [comment]
Can you elaborate a bit, do you have some example what you'd like to achieve?

**Comment by stefanwalther** [comment]
Can you post a mock-up or a screenshot, just indicating what you'd like to achieve? Since Qlik Sense 3.0 will be published soon, I am happy to create a sample widget for this use-case - assuming that it is a better fit for Widgets.

**Comment by stefanwalther** [comment]
Closing, didn't receive any answer.
