### ISSUE TITLE
Setting variables

### ISSUE THREAD

**Issue by jillwoodley** [stefanwalther/sense-navigation#49]
Hi, I am trying to use the buttons to change my variables vTY from 2016 to 2015, and VLY from 2015 to 2014. It's not working - the variables don't change although the page changes. I've read the info but cant see what i am doing wrong

**Comment by stefanwalther** [comment]
Thx for reporting, I'll have a look into it ... Which version of Qlik Sense are you using?

**Comment by jillwoodley** [comment]
Qlik Sense 2.2
Sense-id 2.2.3+build37.release/ms15

**Comment by jillwoodley** [comment]
Any updates?

**Comment by stefanwalther** [comment]
Hi, I have tried it and it works properly for me using Qlik Sense 2.2.
This is how I have done it:

1) Created a variable called `vTest`:
![image](https://cloud.githubusercontent.com/assets/669728/15199307/75735fb2-17dd-11e6-9979-be4d65edf656.png)

2) Created a Text & Image Object to test the current value of the variable:
![image](https://cloud.githubusercontent.com/assets/669728/15199339/aea95494-17dd-11e6-9647-62edb843883a.png)

3) Created a sense-navigation objects using the following settings
![image](https://cloud.githubusercontent.com/assets/669728/15199354/c8f8d7d4-17dd-11e6-8295-65b34f6c00c3.png)

![image](https://cloud.githubusercontent.com/assets/669728/15199365/d8ad2a36-17dd-11e6-9661-743ba6689ec2.png)

As soon I click it the variable gets updated to "23".

What's the difference to what you have been doing?

Regards
Stefan

**Comment by jillwoodley** [comment]
Seems to work for me now ?!? Sorry! You mention Sense 3 .. Do you know when this is coming out? Are there any details of what will be in it?
Many thanks and sorry to waste your time.
Kind regards,
Jill

**Comment by stefanwalther** [comment]
Soon, see here a teaser of Qlik Sense 3.0: https://www.youtube.com/watch?v=uLEmoc0OQ10

**Comment by stefanwalther** [comment]
Closing this now. thx.
