### ISSUE TITLE
Will not install in Qlik Sense Server 2.2.4

### ISSUE THREAD

**Issue by dim33** [stefanwalther/sense-navigation#50]
Unfortunately the load fails in the QMC. I have tried fixing (manually and --fix) with ext-check but the import still fails.

I have also downloaded from the latest version link. This passes the ext-check but still the import fails.

**Comment by stefanwalther** [comment]
Thx for reporting, I will double-check.

**Comment by stefanwalther** [comment]
Cannot reproduce, feel free to re-open, but as of now I cannot find any issue with Qlik Sense 2.2.4
