### ISSUE TITLE
Conditional colours or highlighting

### ISSUE THREAD

**Issue by jillwoodley** [stefanwalther/sense-navigation#52]
Hi Stefan,

I am using your buttons to change variables and consequently change the year of the data. is there anyway of indicating which button is active, bold font or the colour of the button?

Many thanks for any help
Jill

**Comment by stefanwalther** [comment]
Hi, I am afraid that right now there is no possibility to do that. But interesting use case. Can you post a screenshot that I get a better idea what you are trying to achieve?

**Comment by jillwoodley** [comment]
ok i have a page and it doesent make sense for all the data to be displayed at once. So i have three buttons and use a variable in set analysis and the buttons to change the data.

![screenshot](https://cloud.githubusercontent.com/assets/19187719/15900730/75763c0c-2d98-11e6-87ab-d31134d27362.JPG)

i have used this code in the expression label
=if(vType = 'CI', 'COST & LEAKAGE', 'Cost & Leakage')
which turns the button to capitals when pressed but really i would like the words to be bold, or coloured or better still the background going a different colur to show it is active.

**Comment by stefanwalther** [comment]
OK, cannot promise anything, there are other topics I want to focus on first, e.g. allow n actions ...

**Comment by jillwoodley** [comment]
ok thanks - it is not possible today though? is there no code i can add to the lable expression to colour?
i wondered if something like the below was possible and i just didnt get the right syntax
=if(vType = 'CI', 'COST & LEAKAGE'black(), 'Cost & Leakage'red())

**Comment by stefanwalther** [comment]
No, that's unfortunately not possible ...

**Comment by stefanwalther** [comment]
Closing.
