### ISSUE TITLE
Using variable with (select value in field) action.

### ISSUE THREAD

**Issue by ziadsa** [stefanwalther/sense-navigation#53]
Hello Stefan,

I am really thankful for your extensions. they always tickle a lot of my problems.

Can we use variables with the action (select value in field)? if not may you please please add this feature in the next version. because I think it will give us more capacity to use the extension, especially to use the output of another extension (i.e calendar extension). 

Thank you so much.
Ziad Salem.

**Comment by stefanwalther** [comment]
Can you please explain a bit more:

- So you want to define a variable and then ...?

**Comment by ziadsa** [comment]
I want to use Select Value Field action (for example the field is "category" and the value is "Book" ). In the value expression I do not want to use the plain text like ('Book') I want to use {vCategory} variable (let's say I have another three button which give the variable {vCategory} a specific name like (the first button assigning to {vCategory} the value "Book", the second "Clothes" and the third "Electronics"). After that, I press the button select in category field to select the field according to the variable value.

As a second usage and more complex. I have a two timestamp fields and I load the data for one year. If I want to select the data according to a specific interval (i.e from [2016-04-01 00:00:00] to July [2016-07-15 23:59:59]) using your extension I need to write in the value expression [='<2016-04-01 00:00:00'] and in the second timestamp field [='>2016-07-15 23:59:59']. if I want to go more dynamically. Then I need to use another extension which is Calendar_DatePicker (this calendar uses two variables {vFromDate} and {vToDate}). So, I select the date (in format 2016-04-15) using it, then in the expression I concatenate the date with the time with which is always fixed (00:00:00 for the beginning of the period, 23:59:59 for the end). whenever I concatenate the time with the date (in another variable or directly in the value expression), at the end I need to use variables and maybe write some expression in the "Value Expression" of an action which is here in my example "Select Value in Field".

I do not know if it is already exist, I have tried it but I cloud not succeed.

**Comment by stefanwalther** [comment]
OK; this is really a good idea, will add soon.

**Comment by stefanwalther** [comment]
Hi, first of all you can already use variables.
This is a short example:
![image](https://cloud.githubusercontent.com/assets/669728/16857644/7abd7cde-4a21-11e6-9449-66f236aceb5e.png)

![image](https://cloud.githubusercontent.com/assets/669728/16857648/86e016d4-4a21-11e6-8bf2-67a21432c721.png)

**Comment by stefanwalther** [comment]
The second use-case using the calendar is a bit more complex but should be achieved using the same approach. The only problem you probably run into is that date fields are dual fields and selection by the text currently does not work.
