### ISSUE TITLE
Multiple values selection in a field doesn't work for Dates

### ISSUE THREAD

**Issue by hemhund** [stefanwalther/sense-navigation#54]
Hi Stefan,

Great Extension
In My case, it worked great for String selections. But when I used it to select multiple values in a field for Date selections, it doesn't work.
I tried for Number too. It didn't work.
I am using as below.

='123;234;1234'

Let me know if I missed any thing.

Thanks,
Hemanth.

**Comment by stefanwalther** [comment]
Thx, I'll look into that.

**Comment by hemhund** [comment]
Update

I downloaded the recent build. It worked for numbers but not for dates.
So the issue only seems to be with Dates

**Comment by stefanwalther** [comment]
Yes, I made a fix for numbers a while ago (#45). How do you define your dates, can you post an example?

**Comment by hemhund** [comment]
The format is MM/DD/YYYY
I am using the date selection as below for example.

'12/03/2015;3/4/2016'

**Comment by stefanwalther** [comment]
I guess it's a dual type (https://community.qlik.com/blogs/qlikviewdesignblog/2012/11/13/dual), right?

**Comment by stefanwalther** [comment]
Closing, not received any answer.
