### ISSUE TITLE
How to transfer text to another line?

### ISSUE THREAD

**Issue by KseniaVoloshko** [stefanwalther/sense-navigation#55]
Good afternoon! How can I transfer half of the text of the button on the other line? If I can't move with the help of "ENTER"? I have a lot of buttons on the page, with a lot of text. The text doesn't fit in the buttons.

**Comment by stefanwalther** [comment]
Hi, this is currently not possible. I put it on the list of requested enhancements.

**Comment by stefanwalther** [comment]
Added with v0.6.0 (481d0ba2a6fc46789ea34cd004049fb99195e188)
