### ISSUE TITLE
Select Value in Field Not Working

### ISSUE THREAD

**Issue by asanoop24** [stefanwalther/sense-navigation#57]
Hi I am trying to use the 'Select Value in Field' Action to filter the data field [Store Description] for the value 'CSG'. After assigning this action when I click on the button, nothing happens. Can someone please help me out on this?? Its really urgent!!

Thanks in Advance!!

**Comment by stefanwalther** [comment]
Thx for reporting, I'll have a look.
Which version of sense-navigation are you using? I recently have pushed a lot of updates and new versions.

**Comment by asanoop24** [comment]
Hey, I was able to solve the first issue for 'Select Value in Field'. But Can you help with the second issue here -

 Is there any way that can help me 'Exclude Value in Field' Action to select all values in a field except one. 

Any help will be appreciated!!

**Comment by stefanwalther** [comment]
Hi @asanoop24, yes I can help: This action was not implemented, yet. I have added it now with version 0.8.0 of sense-navigation. Give it a try.

https://github.com/stefanwalther/sense-navigation/releases/tag/v0.8.0
