### ISSUE TITLE
Need two more Actions

### ISSUE THREAD

**Issue by qlikpathy** [stefanwalther/sense-navigation#59]
Hi Stefan,
We need two more actions(totally four actions) which will be executed before the navigation behaviour in the sense-navigation extension.
Please help us.

Thanks,

Regards,
Bhupathy B.

**Comment by stefanwalther** [comment]
Beta of v1.0 of sense-navigation already included an "unlimited" amount of actions: Have a look here: https://github.com/stefanwalther/sense-navigation/tree/v1.0

**Comment by swethanagireddy** [comment]
That sounds great. I was looking for the same

**Comment by swethanagireddy** [comment]
Hi Stefan,

I am getting an error message called Invalid visualization after installing this new version of v1.0 of sense navigation. I copy pasted the folder to my extensions folder locally and it doesnt seem to work? Do i need to do anything else?

![capture](https://cloud.githubusercontent.com/assets/22099407/18481815/ab146140-79ab-11e6-9b2e-2507d1966cb8.JPG)

**Comment by swethanagireddy** [comment]
Invalid visualization issue is now fixed after reinstalling Qliksense desktop. However, I still cant see more actions..I found only 2 actions.
![capture](https://cloud.githubusercontent.com/assets/22099407/18484277/bd455b62-79b5-11e6-87ee-fd335137b23c.JPG)

**Comment by swethanagireddy** [comment]
Bhupathy,

can you  please let me know if it worked for you? where you able to add 4 actions?

**Comment by qlikpathy** [comment]
no Swetha..
I couldn't see Third and Fourth Actions in the extension.
still its showing only two actions i.e First Action and Second Action.
 
Thanks,
Regards,
Bhupathy B
 
-----Original Message-----

**Comment by swethanagireddy** [comment]
Looked at the properties.js file and the code seems to be dynamic too..earlier it had only first and second action code..but now it had 'N' number of actions. Dont know if we are doing something wrong. Will wait for Stefan to comment.
