### ISSUE TITLE
Need unlimited actions- Issue with newest version of Sense navigation(v1.0)

### ISSUE THREAD

**Issue by swethanagireddy** [stefanwalther/sense-navigation#60]
Hi Stefan,

I downloaded new version v1.0 of Sheet Navigation + Actions for Qlik Sense and tired to pull the button onto my sheet..I see the extension on the left hand side panel but however when I drag it it shows Invalid visuailization. I also posted on the link below with my concern and also appended a screenshot of the issue I am facing. 
https://github.com/stefanwalther/sense-navigation/issues/59

TIA.
Swetha Nagireddy
Infozone Intelligence

**Comment by swethanagireddy** [comment]
Hi Stefan,

I uninstalled Qliksense desktop and reinstalled it again which therefore fixed the issue of invalid visualization. However, even after using the newest version I still can't add more actions.
![capture](https://cloud.githubusercontent.com/assets/22099407/18483996/9e6b7024-79b4-11e6-95c9-121b6e20415d.JPG)

I can add only 2 actions.

**Comment by stefanwalther** [comment]
Will be solved in #58, you can start testing/using that specific version; feedback is greatly appreciated. Will therefore close this issue.
