### ISSUE TITLE
Export sheet as PDF action

### ISSUE THREAD

**Issue by blunckc1** [stefanwalther/sense-navigation#66]
Hi Stefan,

Wondering if you can add an action to your wonderful extension that will enable the sheet to be exported to PDF?  

Cheers
Carl

**Comment by stefanwalther** [comment]
Hi, no I can unfortunately not add this functionality to sense-navigation, because there is currently no API for that.

**Comment by blunckc1** [comment]
Hi Stefan,

Appreciate the quick reply!

Regards
Carl

Carl Blunck
Senior Workforce Analyst and Systems
Workforce and Organisational Development, People and Culture
Children’s Health Queensland Hospital and Health Service
Level 9 | Centre for Children’s Health Research
Graham Street, South Brisbane QLD 4101
T: 07  3069 7052
E: carl.blunck@health.qld.gov.au<mailto:carl.blunck@health.qld.gov.au>
W: www.childrens.health.qld.gov.au<http://www.childrens.health.qld.gov.au/>
[cid:image001.gif@01D22AEC.D9B26000]

[cid:image002.gif@01D22AEC.D9B26000]<https://www.facebook.com/childrenshealthqld>

[cid:image003.gif@01D22AEC.D9B26000]<https://twitter.com/childhealthqld>

[cid:image004.gif@01D22AEC.D9B26000]<http://www.linkedin.com/company/children's-health-queensland-hospital-and-health-service/>

[cid:image005.gif@01D22AEC.D9B26000]<https://www.instagram.com/ladycilentochildrenshospital/>

[cid:image006.gif@01D22AEC.D9B26000]


Children's Health Queensland acknowledges the Traditional Custodians of the land,
and pays respect to Elders past, present and future.
