### ISSUE TITLE
Feature request: Add-ons > "Data handling"

### ISSUE THREAD

**Issue by boulavogue** [stefanwalther/sense-navigation#67]
A hide/appear option would be a nice feature.

I currently achieve this in "Add-ons > Data handling"  with an expression like 
"COUNT(DISTINCT OrderNumber) =1"  which (if >1 order is selected) deploys a message "Please select an order to see the order details".

It would be to hide these buttons in the same method, only displaying a usable button when condition is met.

Thanks

**Comment by boulavogue** [comment]
Code located : [https://community.qlik.com/thread/177689](https://community.qlik.com/thread/177689)  With warning "not officially supported so this might break in the future".

Tested on 3.0SR1/v3.0.1 Desktop: Working

`addons: {  
     uses: "addons",  
     items: {  
          dataHandling: {  
               uses: "dataHandling"  
          }  
     }  
} `

**Comment by stefanwalther** [comment]
Interesting. No PR received, could you please double-check, thx.

**Comment by boulavogue** [comment]
I'm on mobile for the next day or two but I forked your project and the (small) enhancement is located here https://github.com/boulavogue/sense-navigation/commit/f301f72dcada33d182d89a126164659ece0adf3f

**Comment by stefanwalther** [comment]
OK, thx. Will consider it it #58 .
This is not officially supported (nor documented), but that's probably a pretty tiny risk to add this.

**Comment by stefanwalther** [comment]
Fill be part of v1.0 of sense-navigation ( #58 ).
Thx for suggesting & contributing!
