### ISSUE TITLE
Support for email

### ISSUE THREAD

**Issue by jacekvsp** [stefanwalther/sense-navigation#69]
In swr-sense-navigation.js 
find:
(url.startsWith("http://")||url.startsWith("https://")
chage to:
(url.startsWith("http://")||url.startsWith("https://")||(url.startsWith("mailto://")

Then you can create button that will launch email client. 

in Navigation Action->Open website->Website URL enter mailto://Someone%3Cemail@domain.com%3E?subject=Qlik Question ...&body=Hello Folks,%0A%0AI have a question about Qlik Sense...%0A%0AThank You

Tested with QS 3.1 and works in IE and CHROME.

Syntax: https://en.wikipedia.org/wiki/Uniform_Resource_Identifier
Examples: https://en.wikipedia.org/wiki/Mailto

**Comment by stefanwalther** [comment]
Absolutely valid request, have added it to the #58 branch.
