### ISSUE TITLE
Button size in "QLIK - standard" appearance

### ISSUE THREAD

**Issue by gerhard1969** [stefanwalther/sense-navigation#70]
Buttons (single block-height) are fine in "QLIK-classic" appearance, but when I switch to "QLIK-standard" then half of the button disappears. The button-element needs to be (at least) two blocks high to be completely visible in "QLIK-standard".

**Comment by stefanwalther** [comment]
Yes, I am aware of that, but there is not much I can do about it; I was thinking of adding three different sizes of buttons there. Another option would be to monitor the available space and switch to a link instead if not enough space is available.
What do you think is the best option?

**Comment by apinheiro90** [comment]
After updating the qlik server to 3.1 the buttons size appeared to be cut in half even if i use QLIK-Classic appearance. it seems i need to use also 2 blocks in order to show the full size.
Any idea if this is fixable?

**Comment by apinheiro90** [comment]
After updating the qlik server to 3.1 the buttons size appeared to be cut in half even if i use QLIK-Classic appearance. it seems i need to use also 2 blocks in order to show the full size.
Any idea how can i fix this? Thanks

**Comment by gerhard1969** [comment]
Thanks for your rapid response. I think that a ‘small button’ configuration option is sufficient. Another idea could be to allow multiple buttons in a single visual/element – that way you could control the space around each button within the visual (but I don’t know if that is feasible).

By ther way, like the navigation –even with the “two-block-size” buttons ☺

**Comment by ArielKl1** [comment]
Hi Stefan.
Any news about this issue?

I have the same problem with "QLIK-standard" 

Thanks
Ariel

**Comment by stefanwalther** [comment]
Can you pls try the release-candidate of v1.0 (https://github.com/stefanwalther/sense-navigation/tree/v1.0/build), is this still an issue?

See #58 for more information about v1.0
