### ISSUE TITLE
Set button colour based on function

### ISSUE THREAD

**Issue by Seckito** [stefanwalther/sense-navigation#71]
Hello,

Is there any way to make the button colour change by a function?
I would like to use it as a clicked or not clicked button so the user may know when he has selected it or not.

Thanks in advance. 

Kind regards.

**Comment by stefanwalther** [comment]
Hi, thx for your feedback. Right now this is not supported. I am thinking of the best way how to bring this into sense-navigation. Stay tuned.

**Comment by stefanwalther** [comment]
See #121

**Comment by stefanwalther** [comment]
@Seckito: Closed (for branch v1.0, see #58 ) with #122.
