### ISSUE TITLE
Cannot load extension. 

### ISSUE THREAD

**Issue by WoutV** [stefanwalther/sense-navigation#73]
"failed to import extension. Please check log file"
Importing other extensions still works.

**Comment by stefanwalther** [comment]
I guess you are just downloading the entire GitHub repo and not the files in the `build` directory?

**Comment by neyster** [comment]
I'm receiving the same error. Using 3.1.4. Tried importing the Dev file within build. Error below. 

Duplicate extension (the extension already exists or occurs more than once in the ZIP file): swr-sense-navigation (HTTP code: 400

**Comment by WoutV** [comment]
The error stopped showing. Probably a server issue.
