### ISSUE TITLE
Add more actions

### ISSUE THREAD

**Issue by hnguyen515A** [stefanwalther/sense-navigation#74]
Hi Stefan
Love your extension and I use it throughout my app.
Can you add more actions than just 2? When navigating to a sheet most of the time I need to set the values of more than 2 variables, usually 4 or 5. If you can provide additional actions it'll be awesome!
Thanks.
Hong Nguyen

**Comment by stefanwalther** [comment]
Hi, have a look at v1.0, which actually already includes unlimited actions. I'll try to finalize the v1 ASAP: https://github.com/stefanwalther/sense-navigation/tree/v1.0

Regards
Stefan
