### ISSUE TITLE
Request for documentation pertaining to building locally

### ISSUE THREAD

**Issue by gdw-atwork** [stefanwalther/sense-navigation#76]
Have been working on changes locally but cannot get npm build or gulp build to compile the dev copy.

Thanks in advance

**Comment by stefanwalther** [comment]
A first draft: https://github.com/stefanwalther/sense-extension-contrib#related-projects

Does this help?

**Comment by stefanwalther** [comment]
ping: @gdw-atwork

**Comment by gdw-atwork** [comment]
very nice.  thank you

Sorry for delayed response.
