### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by hartmoli** [stefanwalther/sense-navigation#77]
Hi Stefan

I really like your extension and would like to thanks for your effort. One thing I miss is the setting to modify the height or the width in css style like: height:100%; I have the problem that on a tablet the Buttons are cutted off. I think with this modification to change the height or width manually would solve this issue. 

Best regards, oliver

**Comment by stefanwalther** [comment]
Hi, can you kindly post a screenshot?

Furthermore, did you try the upcoming version 1.0 (https://github.com/stefanwalther/sense-navigation/tree/v1.0)?

**Comment by yorchnova** [comment]
stefan, i think hartmoli is talking about this
![image](https://user-images.githubusercontent.com/18445880/29376504-67ead3cc-827e-11e7-8ffe-16f92ba3aa1e.png)

**Comment by mauro-marson** [comment]
@stefanwalther, i think hartmoli is talking about this (i have a similar behavior).
![2017-08-23 12_19_45-dwh_agita 4 application - dashboard agenzia italia 1 05 _ fogli - qlik sense](https://user-images.githubusercontent.com/4293629/29611326-6a9b9334-87fd-11e7-855a-189d58ccfe04.png)

**Comment by stefanwalther** [comment]
So custom CSS is now supported with the upcoming v1.0 version (see #58). This is certainly not the ideal solution, as this should work better out of the box, but it might help you short term.

I keep this open for reference as I am planning to spend some time on it, let's see if I have a good idea to solve this in a better way.

**Comment by stefanwalther** [comment]
I am closing this as I am not planning to add more functionality related to this issue. It's not that I don't like to meet these requirements, but the public APIs (and I am trying to strictly stick to public APIs in this visualization extension) just don't provide methods to achieve what you are describing ...
At least I don't know how.

If you have better ideas than I have, please feel free to do a PR or certainly just feel free to re-open this PR.

Thx in advance for your understanding and your contribution.
