### ISSUE TITLE
Second Action Function Not Working In Version 3.2

### ISSUE THREAD

**Issue by mertinsa** [stefanwalther/sense-navigation#80]
Hello Stefan the second action function is not working on qlik version 3.2.

Can you please address this issue? I work for a large fortune 500 company that uses this extension in several popular applications.

**Comment by stefanwalther** [comment]
Did you try the new version I am working on https://github.com/stefanwalther/sense-navigation/tree/v1.0 ?

**Comment by stefanwalther** [comment]
Closing as I haven't received any answer. Pls feel to re-open if needed.
