### ISSUE TITLE
Select Value of dimensions - Not working

### ISSUE THREAD

**Issue by ShwetaAPatil** [stefanwalther/sense-navigation#81]
I am unable to filter on any values in a table.  Is this expected as part of this extension? Since the default qlik Sense functionality allows to click on any values, so just wanted to check.  I am using 3.1 version of Qlik Sense.

**Comment by stefanwalther** [comment]
Thx for your feedback, I'll have a look into this issue.

**Comment by stefanwalther** [comment]
What you are describing is not really related to this extension. Closing therefore.
