### ISSUE TITLE
Obejct Positioning in IE11 using Sense Focus App Theme

### ISSUE THREAD

**Issue by itsjustryan** [stefanwalther/sense-navigation#84]
### Description

When using the App Theme of Sense Focus, the buttons are completely visible. it is almost like a border is being put around them causing the object to be pushed out of the frame.

### Steps to Reproduce

1. create object
2. change App theme to sense focus
3. open in IE11
4.if not evident resize window to a smaller frame.

##### Expected behavior

I would expect the button/object to remain in the upper left of the frame.

##### Actual behavior

button gets pushed down and to the right and part of the button s out of view.

##### Operating system

```
[X] Windows
[ ] OSX
[ ] Linux
```
##### Qlik Sense

```
[ ] Desktop
[x] Enterprise
```

##### Browser

```
[ ] Chrome
[ ] Firefox
[x] Internet Explorer
[ ] Edge
[ ] Others: XXX
```

### Versions

* Browser: ie11.0.96
* Qlik Sense: 3.2 SR3
* Operating system: Windows 7 SP1
* [Other relevant versions]
![sense button](https://user-images.githubusercontent.com/10130152/26981322-6442adda-4cfa-11e7-944e-ca234df750bc.PNG)

**Comment by stefanwalther** [comment]
Thx for reporting this, I'll have a look.

**Comment by stefanwalther** [comment]
Hmm, I looked into this issue. As this is "just" the styling of this theme, there is really not much I can/want to do here. Really don't want to inject/modify the theme of this style.

If you give the buttons enough space, it seems to work properly for me:
![image](https://user-images.githubusercontent.com/669728/35318783-e148260c-00aa-11e8-9706-20a16a9ee137.png)

I am therefore closing this issue for now. Please feel to re-open or file a PR if you have an idea, how this can be fixed properly without modifying the theme.
