### ISSUE TITLE
Import in Qlik Sense server not working

### ISSUE THREAD

**Issue by MathDataArt** [stefanwalther/sense-navigation#88]
### Description

Importing latest zip file in server fails.

### Steps to Reproduce

1. Download latest zip file
2. Import zip in QMC
3. Task fails

##### Expected behavior

Successful import

##### Actual behavior

"Failed to import the extension. Please check the log file"

### Versions

* Qlik Sense: 3.2 SR4   and 3.1 IR
Tried both

**Comment by stefanwalther** [comment]
Did you download the .zip file from the ./build directory or did you just download the entire project from GitHub?

**Comment by stefanwalther** [comment]
Ping @MathDataArt ^

**Comment by stefanwalther** [comment]
Closing as no answer was provided.
