### ISSUE TITLE
Customized Button Colors

### ISSUE THREAD

**Issue by Kwschramm** [stefanwalther/sense-navigation#89]
I love this extension and use it all the time.  Works fine in 3.2 SR3 BTW.  Are there any plans to be able to customize the button colors?  We have a couple of clients that have a particular blue that they use for internal application branding.  Thanks in advance for your response and consideration.

**Comment by stefanwalther** [comment]
For now, I have no plans to bring in this functionality, although I absolutely understand that this would be a nice feature. But first I have to push out the long awaited v1 of this extension (https://github.com/stefanwalther/sense-navigation/tree/v1.0).

**Comment by stefanwalther** [comment]
See #121

**Comment by stefanwalther** [comment]
@Kwschramm: Closed (for branch v1.0, see #58 ) with #122.
