### ISSUE TITLE
This Extension is not working

### ISSUE THREAD

**Issue by GSangeetha** [stefanwalther/sense-navigation#90]
Extension Not Working
Trying to use this extension in project, but its not working. None of the actions are reflecting. 
Using Qliksense Dev Hub for development.
Qliksense version: 3.1 SR5

Pls help me to resolve this issue. We are using Extension in project, client want to see this extension. We waiting for response.

### Steps to Reproduce

1. [Step one]
2. [Step two]
3. ...

##### Expected behavior

[What you expected to happen]

##### Actual behavior

[What actually happened]

##### Operating system

```
[ ] Windows
[ ] OSX
[ ] Linux
```
##### Qlik Sense

```
[ ] Desktop
[ ] Enterprise
```

##### Browser

```
[ ] Chrome
[ ] Firefox
[ ] Internet Explorer
[ ] Edge
[ ] Others: XXX
```

### Versions

* Browser: 
* Qlik Sense: 
* Operating system: 
* [Other relevant versions]

**Comment by stefanwalther** [comment]
What exactly did you load in Dev-Hub?

**Comment by stefanwalther** [comment]
Ping @GSangeetha ^

**Comment by stefanwalther** [comment]
Closing as I didn't receive any answer.
Please feel to re-open if needed.
