### ISSUE TITLE
Support for more than 10 Columns

### ISSUE THREAD

**Issue by patrick-ryan1** [stefanwalther/sense-navigation#92]
### Currently only 10 columns of data appear when using QSTable.

[Description of the issue]

### Steps to Reproduce
Create a table with 11 columns of data.  The 11th will be filled with blank data.
##### Qlik Sense

Is there a way to extend?
```
[ ] Desktop
[x ] Enterprise 3.3
```

##### Browser

```
[ ] Chrome
[ ] Firefox
[ ] Internet Explorer
[ ] Edge
[ ] Others: XXX
```

### Versions

* Extension version: 
* Browser: 
* Qlik Sense: 
* Operating system: 
* [Other relevant versions]

**Comment by stefanwalther** [comment]
Sorry, I don't understand. What is QSTable? Did you maybe want to post an issue for another extension?

**Comment by stefanwalther** [comment]
Closing because didn't receive any answer; pls feel free to re-open if needed.
