### ISSUE TITLE
working on my app in my QLIK sense desktop - does'nt work for other users ?

### ISSUE THREAD

**Issue by philgood34** [stefanwalther/sense-navigation#97]
I created a app with your great extension . It is working perfectly for me

i sent my app.qvf to other users who drag and drop it in their qlik sense desktop. for all of them the extension does'nt work ??? (buttons do not  appear correctly )

is there any setting or anything to do ?

Regards

 

##### Operating system

```
[ ] Windows 10

##### Qlik Sense

```
[ ] Desktop

```

Browser

```
[ ] Chrome

```


### Versions

* Extension version: 

* Qlik Sense:

**Comment by csilva91** [comment]
Make sure the user has the extension installed

**Comment by philgood34** [comment]
Of course. ... you are right !
I did not make sure !
Thank's
